/*
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.50
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from './ApiClient';
import {AnyOfCreateAssistantRequestModel} from './model/AnyOfCreateAssistantRequestModel';
import {AnyOfCreateChatCompletionRequestModel} from './model/AnyOfCreateChatCompletionRequestModel';
import {AnyOfCreateCompletionRequestModel} from './model/AnyOfCreateCompletionRequestModel';
import {AnyOfCreateEditRequestModel} from './model/AnyOfCreateEditRequestModel';
import {AnyOfCreateEmbeddingRequestModel} from './model/AnyOfCreateEmbeddingRequestModel';
import {AnyOfCreateFineTuneRequestModel} from './model/AnyOfCreateFineTuneRequestModel';
import {AnyOfCreateFineTuningJobRequestModel} from './model/AnyOfCreateFineTuningJobRequestModel';
import {AnyOfCreateImageEditRequestModel} from './model/AnyOfCreateImageEditRequestModel';
import {AnyOfCreateImageRequestModel} from './model/AnyOfCreateImageRequestModel';
import {AnyOfCreateImageVariationRequestModel} from './model/AnyOfCreateImageVariationRequestModel';
import {AnyOfCreateModerationRequestModel} from './model/AnyOfCreateModerationRequestModel';
import {AnyOfCreateSpeechRequestModel} from './model/AnyOfCreateSpeechRequestModel';
import {AnyOfCreateTranscriptionRequestModel} from './model/AnyOfCreateTranscriptionRequestModel';
import {AnyOfCreateTranslationRequestModel} from './model/AnyOfCreateTranslationRequestModel';
import {AnyOfModifyAssistantRequestModel} from './model/AnyOfModifyAssistantRequestModel';
import {AssistantFileObject} from './model/AssistantFileObject';
import {AssistantObject} from './model/AssistantObject';
import {AssistantToolsCode} from './model/AssistantToolsCode';
import {AssistantToolsFunction} from './model/AssistantToolsFunction';
import {AssistantToolsFunctionFunction} from './model/AssistantToolsFunctionFunction';
import {AssistantToolsRetrieval} from './model/AssistantToolsRetrieval';
import {ChatCompletionFunctionCallOption} from './model/ChatCompletionFunctionCallOption';
import {ChatCompletionFunctionParameters} from './model/ChatCompletionFunctionParameters';
import {ChatCompletionFunctions} from './model/ChatCompletionFunctions';
import {ChatCompletionMessageToolCall} from './model/ChatCompletionMessageToolCall';
import {ChatCompletionMessageToolCallChunk} from './model/ChatCompletionMessageToolCallChunk';
import {ChatCompletionMessageToolCallChunkFunction} from './model/ChatCompletionMessageToolCallChunkFunction';
import {ChatCompletionMessageToolCallFunction} from './model/ChatCompletionMessageToolCallFunction';
import {ChatCompletionMessageToolCalls} from './model/ChatCompletionMessageToolCalls';
import {ChatCompletionNamedToolChoice} from './model/ChatCompletionNamedToolChoice';
import {ChatCompletionNamedToolChoiceFunction} from './model/ChatCompletionNamedToolChoiceFunction';
import {ChatCompletionRequestAssistantMessage} from './model/ChatCompletionRequestAssistantMessage';
import {ChatCompletionRequestAssistantMessageFunctionCall} from './model/ChatCompletionRequestAssistantMessageFunctionCall';
import {ChatCompletionRequestFunctionMessage} from './model/ChatCompletionRequestFunctionMessage';
import {ChatCompletionRequestMessage} from './model/ChatCompletionRequestMessage';
import {ChatCompletionRequestMessageContentPart} from './model/ChatCompletionRequestMessageContentPart';
import {ChatCompletionRequestMessageContentPartImage} from './model/ChatCompletionRequestMessageContentPartImage';
import {ChatCompletionRequestMessageContentPartImageImageUrl} from './model/ChatCompletionRequestMessageContentPartImageImageUrl';
import {ChatCompletionRequestMessageContentPartText} from './model/ChatCompletionRequestMessageContentPartText';
import {ChatCompletionRequestSystemMessage} from './model/ChatCompletionRequestSystemMessage';
import {ChatCompletionRequestToolMessage} from './model/ChatCompletionRequestToolMessage';
import {ChatCompletionRequestUserMessage} from './model/ChatCompletionRequestUserMessage';
import {ChatCompletionResponseMessage} from './model/ChatCompletionResponseMessage';
import {ChatCompletionRole} from './model/ChatCompletionRole';
import {ChatCompletionStreamResponseDelta} from './model/ChatCompletionStreamResponseDelta';
import {ChatCompletionStreamResponseDeltaFunctionCall} from './model/ChatCompletionStreamResponseDeltaFunctionCall';
import {ChatCompletionTool} from './model/ChatCompletionTool';
import {ChatCompletionToolChoiceOption} from './model/ChatCompletionToolChoiceOption';
import {ChatCompletionToolFunction} from './model/ChatCompletionToolFunction';
import {CompletionUsage} from './model/CompletionUsage';
import {CreateAssistantFileRequest} from './model/CreateAssistantFileRequest';
import {CreateAssistantRequest} from './model/CreateAssistantRequest';
import {CreateChatCompletionFunctionResponse} from './model/CreateChatCompletionFunctionResponse';
import {CreateChatCompletionFunctionResponseChoices} from './model/CreateChatCompletionFunctionResponseChoices';
import {CreateChatCompletionImageResponse} from './model/CreateChatCompletionImageResponse';
import {CreateChatCompletionRequest} from './model/CreateChatCompletionRequest';
import {CreateChatCompletionRequestResponseFormat} from './model/CreateChatCompletionRequestResponseFormat';
import {CreateChatCompletionResponse} from './model/CreateChatCompletionResponse';
import {CreateChatCompletionResponseChoices} from './model/CreateChatCompletionResponseChoices';
import {CreateChatCompletionStreamResponse} from './model/CreateChatCompletionStreamResponse';
import {CreateChatCompletionStreamResponseChoices} from './model/CreateChatCompletionStreamResponseChoices';
import {CreateCompletionRequest} from './model/CreateCompletionRequest';
import {CreateCompletionResponse} from './model/CreateCompletionResponse';
import {CreateCompletionResponseChoices} from './model/CreateCompletionResponseChoices';
import {CreateCompletionResponseLogprobs} from './model/CreateCompletionResponseLogprobs';
import {CreateEditRequest} from './model/CreateEditRequest';
import {CreateEditResponse} from './model/CreateEditResponse';
import {CreateEditResponseChoices} from './model/CreateEditResponseChoices';
import {CreateEmbeddingRequest} from './model/CreateEmbeddingRequest';
import {CreateEmbeddingResponse} from './model/CreateEmbeddingResponse';
import {CreateEmbeddingResponseUsage} from './model/CreateEmbeddingResponseUsage';
import {CreateFileRequest} from './model/CreateFileRequest';
import {CreateFineTuneRequest} from './model/CreateFineTuneRequest';
import {CreateFineTuneRequestHyperparameters} from './model/CreateFineTuneRequestHyperparameters';
import {CreateFineTuningJobRequest} from './model/CreateFineTuningJobRequest';
import {CreateFineTuningJobRequestHyperparameters} from './model/CreateFineTuningJobRequestHyperparameters';
import {CreateImageEditRequest} from './model/CreateImageEditRequest';
import {CreateImageRequest} from './model/CreateImageRequest';
import {CreateImageVariationRequest} from './model/CreateImageVariationRequest';
import {CreateMessageRequest} from './model/CreateMessageRequest';
import {CreateModerationRequest} from './model/CreateModerationRequest';
import {CreateModerationResponse} from './model/CreateModerationResponse';
import {CreateModerationResponseCategories} from './model/CreateModerationResponseCategories';
import {CreateModerationResponseCategoryScores} from './model/CreateModerationResponseCategoryScores';
import {CreateModerationResponseResults} from './model/CreateModerationResponseResults';
import {CreateRunRequest} from './model/CreateRunRequest';
import {CreateSpeechRequest} from './model/CreateSpeechRequest';
import {CreateThreadAndRunRequest} from './model/CreateThreadAndRunRequest';
import {CreateThreadRequest} from './model/CreateThreadRequest';
import {CreateTranscriptionRequest} from './model/CreateTranscriptionRequest';
import {CreateTranscriptionResponse} from './model/CreateTranscriptionResponse';
import {CreateTranslationRequest} from './model/CreateTranslationRequest';
import {CreateTranslationResponse} from './model/CreateTranslationResponse';
import {DeleteAssistantFileResponse} from './model/DeleteAssistantFileResponse';
import {DeleteAssistantResponse} from './model/DeleteAssistantResponse';
import {DeleteFileResponse} from './model/DeleteFileResponse';
import {DeleteMessageResponse} from './model/DeleteMessageResponse';
import {DeleteModelResponse} from './model/DeleteModelResponse';
import {DeleteThreadResponse} from './model/DeleteThreadResponse';
import {Embedding} from './model/Embedding';
import {Error} from './model/Error';
import {ErrorResponse} from './model/ErrorResponse';
import {FineTune} from './model/FineTune';
import {FineTuneEvent} from './model/FineTuneEvent';
import {FineTuneHyperparams} from './model/FineTuneHyperparams';
import {FineTuningJob} from './model/FineTuningJob';
import {FineTuningJobError} from './model/FineTuningJobError';
import {FineTuningJobEvent} from './model/FineTuningJobEvent';
import {FineTuningJobHyperparameters} from './model/FineTuningJobHyperparameters';
import {Image} from './model/Image';
import {ImagesResponse} from './model/ImagesResponse';
import {ListAssistantFilesResponse} from './model/ListAssistantFilesResponse';
import {ListAssistantsResponse} from './model/ListAssistantsResponse';
import {ListFilesResponse} from './model/ListFilesResponse';
import {ListFineTuneEventsResponse} from './model/ListFineTuneEventsResponse';
import {ListFineTunesResponse} from './model/ListFineTunesResponse';
import {ListFineTuningJobEventsResponse} from './model/ListFineTuningJobEventsResponse';
import {ListMessageFilesResponse} from './model/ListMessageFilesResponse';
import {ListMessagesResponse} from './model/ListMessagesResponse';
import {ListModelsResponse} from './model/ListModelsResponse';
import {ListPaginatedFineTuningJobsResponse} from './model/ListPaginatedFineTuningJobsResponse';
import {ListRunStepsResponse} from './model/ListRunStepsResponse';
import {ListRunsResponse} from './model/ListRunsResponse';
import {ListThreadsResponse} from './model/ListThreadsResponse';
import {MessageContentImageFileObject} from './model/MessageContentImageFileObject';
import {MessageContentImageFileObjectImageFile} from './model/MessageContentImageFileObjectImageFile';
import {MessageContentTextAnnotationsFileCitationObject} from './model/MessageContentTextAnnotationsFileCitationObject';
import {MessageContentTextAnnotationsFileCitationObjectFileCitation} from './model/MessageContentTextAnnotationsFileCitationObjectFileCitation';
import {MessageContentTextAnnotationsFilePathObject} from './model/MessageContentTextAnnotationsFilePathObject';
import {MessageContentTextAnnotationsFilePathObjectFilePath} from './model/MessageContentTextAnnotationsFilePathObjectFilePath';
import {MessageContentTextObject} from './model/MessageContentTextObject';
import {MessageContentTextObjectText} from './model/MessageContentTextObjectText';
import {MessageFileObject} from './model/MessageFileObject';
import {MessageObject} from './model/MessageObject';
import {Model} from './model/Model';
import {ModifyAssistantRequest} from './model/ModifyAssistantRequest';
import {ModifyMessageRequest} from './model/ModifyMessageRequest';
import {ModifyRunRequest} from './model/ModifyRunRequest';
import {ModifyThreadRequest} from './model/ModifyThreadRequest';
import {OneOfAssistantObjectToolsItems} from './model/OneOfAssistantObjectToolsItems';
import {OneOfChatCompletionRequestUserMessageContent} from './model/OneOfChatCompletionRequestUserMessageContent';
import {OneOfCreateAssistantRequestToolsItems} from './model/OneOfCreateAssistantRequestToolsItems';
import {OneOfCreateChatCompletionRequestFunctionCall} from './model/OneOfCreateChatCompletionRequestFunctionCall';
import {OneOfCreateChatCompletionRequestStop} from './model/OneOfCreateChatCompletionRequestStop';
import {OneOfCreateCompletionRequestPrompt} from './model/OneOfCreateCompletionRequestPrompt';
import {OneOfCreateCompletionRequestStop} from './model/OneOfCreateCompletionRequestStop';
import {OneOfCreateEmbeddingRequestInput} from './model/OneOfCreateEmbeddingRequestInput';
import {OneOfCreateFineTuneRequestHyperparametersNEpochs} from './model/OneOfCreateFineTuneRequestHyperparametersNEpochs';
import {OneOfCreateFineTuningJobRequestHyperparametersBatchSize} from './model/OneOfCreateFineTuningJobRequestHyperparametersBatchSize';
import {OneOfCreateFineTuningJobRequestHyperparametersLearningRateMultiplier} from './model/OneOfCreateFineTuningJobRequestHyperparametersLearningRateMultiplier';
import {OneOfCreateFineTuningJobRequestHyperparametersNEpochs} from './model/OneOfCreateFineTuningJobRequestHyperparametersNEpochs';
import {OneOfCreateModerationRequestInput} from './model/OneOfCreateModerationRequestInput';
import {OneOfCreateRunRequestToolsItems} from './model/OneOfCreateRunRequestToolsItems';
import {OneOfCreateThreadAndRunRequestToolsItems} from './model/OneOfCreateThreadAndRunRequestToolsItems';
import {OneOfFineTuningJobHyperparametersNEpochs} from './model/OneOfFineTuningJobHyperparametersNEpochs';
import {OneOfMessageContentTextObjectTextAnnotationsItems} from './model/OneOfMessageContentTextObjectTextAnnotationsItems';
import {OneOfMessageObjectContentItems} from './model/OneOfMessageObjectContentItems';
import {OneOfModifyAssistantRequestToolsItems} from './model/OneOfModifyAssistantRequestToolsItems';
import {OneOfRunObjectToolsItems} from './model/OneOfRunObjectToolsItems';
import {OneOfRunStepDetailsToolCallsCodeObjectCodeInterpreterOutputsItems} from './model/OneOfRunStepDetailsToolCallsCodeObjectCodeInterpreterOutputsItems';
import {OneOfRunStepDetailsToolCallsObjectToolCallsItems} from './model/OneOfRunStepDetailsToolCallsObjectToolCallsItems';
import {OneOfRunStepObjectStepDetails} from './model/OneOfRunStepObjectStepDetails';
import {OpenAIFile} from './model/OpenAIFile';
import {RunObject} from './model/RunObject';
import {RunObjectLastError} from './model/RunObjectLastError';
import {RunObjectRequiredAction} from './model/RunObjectRequiredAction';
import {RunObjectRequiredActionSubmitToolOutputs} from './model/RunObjectRequiredActionSubmitToolOutputs';
import {RunStepDetailsMessageCreationObject} from './model/RunStepDetailsMessageCreationObject';
import {RunStepDetailsMessageCreationObjectMessageCreation} from './model/RunStepDetailsMessageCreationObjectMessageCreation';
import {RunStepDetailsToolCallsCodeObject} from './model/RunStepDetailsToolCallsCodeObject';
import {RunStepDetailsToolCallsCodeObjectCodeInterpreter} from './model/RunStepDetailsToolCallsCodeObjectCodeInterpreter';
import {RunStepDetailsToolCallsCodeOutputImageObject} from './model/RunStepDetailsToolCallsCodeOutputImageObject';
import {RunStepDetailsToolCallsCodeOutputImageObjectImage} from './model/RunStepDetailsToolCallsCodeOutputImageObjectImage';
import {RunStepDetailsToolCallsCodeOutputLogsObject} from './model/RunStepDetailsToolCallsCodeOutputLogsObject';
import {RunStepDetailsToolCallsFunctionObject} from './model/RunStepDetailsToolCallsFunctionObject';
import {RunStepDetailsToolCallsFunctionObjectFunction} from './model/RunStepDetailsToolCallsFunctionObjectFunction';
import {RunStepDetailsToolCallsObject} from './model/RunStepDetailsToolCallsObject';
import {RunStepDetailsToolCallsRetrievalObject} from './model/RunStepDetailsToolCallsRetrievalObject';
import {RunStepObject} from './model/RunStepObject';
import {RunStepObjectLastError} from './model/RunStepObjectLastError';
import {RunToolCallObject} from './model/RunToolCallObject';
import {RunToolCallObjectFunction} from './model/RunToolCallObjectFunction';
import {SubmitToolOutputsRunRequest} from './model/SubmitToolOutputsRunRequest';
import {SubmitToolOutputsRunRequestToolOutputs} from './model/SubmitToolOutputsRunRequestToolOutputs';
import {ThreadObject} from './model/ThreadObject';
import {AssistantApi} from './api/AssistantApi';
import {AssistantsApi} from './api/AssistantsApi';
import {AudioApi} from './api/AudioApi';
import {ChatApi} from './api/ChatApi';
import {CompletionsApi} from './api/CompletionsApi';
import {EditsApi} from './api/EditsApi';
import {EmbeddingsApi} from './api/EmbeddingsApi';
import {FilesApi} from './api/FilesApi';
import {FineTunesApi} from './api/FineTunesApi';
import {FineTuningApi} from './api/FineTuningApi';
import {ImagesApi} from './api/ImagesApi';
import {ModelsApi} from './api/ModelsApi';
import {ModerationsApi} from './api/ModerationsApi';

/**
* The_OpenAI_REST_API__Please_see_httpsplatform_openai_comdocsapi_reference_for_more_details_.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var OpenAiApi = require('index'); // See note below*.
* var xxxSvc = new OpenAiApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new OpenAiApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new OpenAiApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new OpenAiApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 2.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The AnyOfCreateAssistantRequestModel model constructor.
     * @property {module:model/AnyOfCreateAssistantRequestModel}
     */
    AnyOfCreateAssistantRequestModel,

    /**
     * The AnyOfCreateChatCompletionRequestModel model constructor.
     * @property {module:model/AnyOfCreateChatCompletionRequestModel}
     */
    AnyOfCreateChatCompletionRequestModel,

    /**
     * The AnyOfCreateCompletionRequestModel model constructor.
     * @property {module:model/AnyOfCreateCompletionRequestModel}
     */
    AnyOfCreateCompletionRequestModel,

    /**
     * The AnyOfCreateEditRequestModel model constructor.
     * @property {module:model/AnyOfCreateEditRequestModel}
     */
    AnyOfCreateEditRequestModel,

    /**
     * The AnyOfCreateEmbeddingRequestModel model constructor.
     * @property {module:model/AnyOfCreateEmbeddingRequestModel}
     */
    AnyOfCreateEmbeddingRequestModel,

    /**
     * The AnyOfCreateFineTuneRequestModel model constructor.
     * @property {module:model/AnyOfCreateFineTuneRequestModel}
     */
    AnyOfCreateFineTuneRequestModel,

    /**
     * The AnyOfCreateFineTuningJobRequestModel model constructor.
     * @property {module:model/AnyOfCreateFineTuningJobRequestModel}
     */
    AnyOfCreateFineTuningJobRequestModel,

    /**
     * The AnyOfCreateImageEditRequestModel model constructor.
     * @property {module:model/AnyOfCreateImageEditRequestModel}
     */
    AnyOfCreateImageEditRequestModel,

    /**
     * The AnyOfCreateImageRequestModel model constructor.
     * @property {module:model/AnyOfCreateImageRequestModel}
     */
    AnyOfCreateImageRequestModel,

    /**
     * The AnyOfCreateImageVariationRequestModel model constructor.
     * @property {module:model/AnyOfCreateImageVariationRequestModel}
     */
    AnyOfCreateImageVariationRequestModel,

    /**
     * The AnyOfCreateModerationRequestModel model constructor.
     * @property {module:model/AnyOfCreateModerationRequestModel}
     */
    AnyOfCreateModerationRequestModel,

    /**
     * The AnyOfCreateSpeechRequestModel model constructor.
     * @property {module:model/AnyOfCreateSpeechRequestModel}
     */
    AnyOfCreateSpeechRequestModel,

    /**
     * The AnyOfCreateTranscriptionRequestModel model constructor.
     * @property {module:model/AnyOfCreateTranscriptionRequestModel}
     */
    AnyOfCreateTranscriptionRequestModel,

    /**
     * The AnyOfCreateTranslationRequestModel model constructor.
     * @property {module:model/AnyOfCreateTranslationRequestModel}
     */
    AnyOfCreateTranslationRequestModel,

    /**
     * The AnyOfModifyAssistantRequestModel model constructor.
     * @property {module:model/AnyOfModifyAssistantRequestModel}
     */
    AnyOfModifyAssistantRequestModel,

    /**
     * The AssistantFileObject model constructor.
     * @property {module:model/AssistantFileObject}
     */
    AssistantFileObject,

    /**
     * The AssistantObject model constructor.
     * @property {module:model/AssistantObject}
     */
    AssistantObject,

    /**
     * The AssistantToolsCode model constructor.
     * @property {module:model/AssistantToolsCode}
     */
    AssistantToolsCode,

    /**
     * The AssistantToolsFunction model constructor.
     * @property {module:model/AssistantToolsFunction}
     */
    AssistantToolsFunction,

    /**
     * The AssistantToolsFunctionFunction model constructor.
     * @property {module:model/AssistantToolsFunctionFunction}
     */
    AssistantToolsFunctionFunction,

    /**
     * The AssistantToolsRetrieval model constructor.
     * @property {module:model/AssistantToolsRetrieval}
     */
    AssistantToolsRetrieval,

    /**
     * The ChatCompletionFunctionCallOption model constructor.
     * @property {module:model/ChatCompletionFunctionCallOption}
     */
    ChatCompletionFunctionCallOption,

    /**
     * The ChatCompletionFunctionParameters model constructor.
     * @property {module:model/ChatCompletionFunctionParameters}
     */
    ChatCompletionFunctionParameters,

    /**
     * The ChatCompletionFunctions model constructor.
     * @property {module:model/ChatCompletionFunctions}
     */
    ChatCompletionFunctions,

    /**
     * The ChatCompletionMessageToolCall model constructor.
     * @property {module:model/ChatCompletionMessageToolCall}
     */
    ChatCompletionMessageToolCall,

    /**
     * The ChatCompletionMessageToolCallChunk model constructor.
     * @property {module:model/ChatCompletionMessageToolCallChunk}
     */
    ChatCompletionMessageToolCallChunk,

    /**
     * The ChatCompletionMessageToolCallChunkFunction model constructor.
     * @property {module:model/ChatCompletionMessageToolCallChunkFunction}
     */
    ChatCompletionMessageToolCallChunkFunction,

    /**
     * The ChatCompletionMessageToolCallFunction model constructor.
     * @property {module:model/ChatCompletionMessageToolCallFunction}
     */
    ChatCompletionMessageToolCallFunction,

    /**
     * The ChatCompletionMessageToolCalls model constructor.
     * @property {module:model/ChatCompletionMessageToolCalls}
     */
    ChatCompletionMessageToolCalls,

    /**
     * The ChatCompletionNamedToolChoice model constructor.
     * @property {module:model/ChatCompletionNamedToolChoice}
     */
    ChatCompletionNamedToolChoice,

    /**
     * The ChatCompletionNamedToolChoiceFunction model constructor.
     * @property {module:model/ChatCompletionNamedToolChoiceFunction}
     */
    ChatCompletionNamedToolChoiceFunction,

    /**
     * The ChatCompletionRequestAssistantMessage model constructor.
     * @property {module:model/ChatCompletionRequestAssistantMessage}
     */
    ChatCompletionRequestAssistantMessage,

    /**
     * The ChatCompletionRequestAssistantMessageFunctionCall model constructor.
     * @property {module:model/ChatCompletionRequestAssistantMessageFunctionCall}
     */
    ChatCompletionRequestAssistantMessageFunctionCall,

    /**
     * The ChatCompletionRequestFunctionMessage model constructor.
     * @property {module:model/ChatCompletionRequestFunctionMessage}
     */
    ChatCompletionRequestFunctionMessage,

    /**
     * The ChatCompletionRequestMessage model constructor.
     * @property {module:model/ChatCompletionRequestMessage}
     */
    ChatCompletionRequestMessage,

    /**
     * The ChatCompletionRequestMessageContentPart model constructor.
     * @property {module:model/ChatCompletionRequestMessageContentPart}
     */
    ChatCompletionRequestMessageContentPart,

    /**
     * The ChatCompletionRequestMessageContentPartImage model constructor.
     * @property {module:model/ChatCompletionRequestMessageContentPartImage}
     */
    ChatCompletionRequestMessageContentPartImage,

    /**
     * The ChatCompletionRequestMessageContentPartImageImageUrl model constructor.
     * @property {module:model/ChatCompletionRequestMessageContentPartImageImageUrl}
     */
    ChatCompletionRequestMessageContentPartImageImageUrl,

    /**
     * The ChatCompletionRequestMessageContentPartText model constructor.
     * @property {module:model/ChatCompletionRequestMessageContentPartText}
     */
    ChatCompletionRequestMessageContentPartText,

    /**
     * The ChatCompletionRequestSystemMessage model constructor.
     * @property {module:model/ChatCompletionRequestSystemMessage}
     */
    ChatCompletionRequestSystemMessage,

    /**
     * The ChatCompletionRequestToolMessage model constructor.
     * @property {module:model/ChatCompletionRequestToolMessage}
     */
    ChatCompletionRequestToolMessage,

    /**
     * The ChatCompletionRequestUserMessage model constructor.
     * @property {module:model/ChatCompletionRequestUserMessage}
     */
    ChatCompletionRequestUserMessage,

    /**
     * The ChatCompletionResponseMessage model constructor.
     * @property {module:model/ChatCompletionResponseMessage}
     */
    ChatCompletionResponseMessage,

    /**
     * The ChatCompletionRole model constructor.
     * @property {module:model/ChatCompletionRole}
     */
    ChatCompletionRole,

    /**
     * The ChatCompletionStreamResponseDelta model constructor.
     * @property {module:model/ChatCompletionStreamResponseDelta}
     */
    ChatCompletionStreamResponseDelta,

    /**
     * The ChatCompletionStreamResponseDeltaFunctionCall model constructor.
     * @property {module:model/ChatCompletionStreamResponseDeltaFunctionCall}
     */
    ChatCompletionStreamResponseDeltaFunctionCall,

    /**
     * The ChatCompletionTool model constructor.
     * @property {module:model/ChatCompletionTool}
     */
    ChatCompletionTool,

    /**
     * The ChatCompletionToolChoiceOption model constructor.
     * @property {module:model/ChatCompletionToolChoiceOption}
     */
    ChatCompletionToolChoiceOption,

    /**
     * The ChatCompletionToolFunction model constructor.
     * @property {module:model/ChatCompletionToolFunction}
     */
    ChatCompletionToolFunction,

    /**
     * The CompletionUsage model constructor.
     * @property {module:model/CompletionUsage}
     */
    CompletionUsage,

    /**
     * The CreateAssistantFileRequest model constructor.
     * @property {module:model/CreateAssistantFileRequest}
     */
    CreateAssistantFileRequest,

    /**
     * The CreateAssistantRequest model constructor.
     * @property {module:model/CreateAssistantRequest}
     */
    CreateAssistantRequest,

    /**
     * The CreateChatCompletionFunctionResponse model constructor.
     * @property {module:model/CreateChatCompletionFunctionResponse}
     */
    CreateChatCompletionFunctionResponse,

    /**
     * The CreateChatCompletionFunctionResponseChoices model constructor.
     * @property {module:model/CreateChatCompletionFunctionResponseChoices}
     */
    CreateChatCompletionFunctionResponseChoices,

    /**
     * The CreateChatCompletionImageResponse model constructor.
     * @property {module:model/CreateChatCompletionImageResponse}
     */
    CreateChatCompletionImageResponse,

    /**
     * The CreateChatCompletionRequest model constructor.
     * @property {module:model/CreateChatCompletionRequest}
     */
    CreateChatCompletionRequest,

    /**
     * The CreateChatCompletionRequestResponseFormat model constructor.
     * @property {module:model/CreateChatCompletionRequestResponseFormat}
     */
    CreateChatCompletionRequestResponseFormat,

    /**
     * The CreateChatCompletionResponse model constructor.
     * @property {module:model/CreateChatCompletionResponse}
     */
    CreateChatCompletionResponse,

    /**
     * The CreateChatCompletionResponseChoices model constructor.
     * @property {module:model/CreateChatCompletionResponseChoices}
     */
    CreateChatCompletionResponseChoices,

    /**
     * The CreateChatCompletionStreamResponse model constructor.
     * @property {module:model/CreateChatCompletionStreamResponse}
     */
    CreateChatCompletionStreamResponse,

    /**
     * The CreateChatCompletionStreamResponseChoices model constructor.
     * @property {module:model/CreateChatCompletionStreamResponseChoices}
     */
    CreateChatCompletionStreamResponseChoices,

    /**
     * The CreateCompletionRequest model constructor.
     * @property {module:model/CreateCompletionRequest}
     */
    CreateCompletionRequest,

    /**
     * The CreateCompletionResponse model constructor.
     * @property {module:model/CreateCompletionResponse}
     */
    CreateCompletionResponse,

    /**
     * The CreateCompletionResponseChoices model constructor.
     * @property {module:model/CreateCompletionResponseChoices}
     */
    CreateCompletionResponseChoices,

    /**
     * The CreateCompletionResponseLogprobs model constructor.
     * @property {module:model/CreateCompletionResponseLogprobs}
     */
    CreateCompletionResponseLogprobs,

    /**
     * The CreateEditRequest model constructor.
     * @property {module:model/CreateEditRequest}
     */
    CreateEditRequest,

    /**
     * The CreateEditResponse model constructor.
     * @property {module:model/CreateEditResponse}
     */
    CreateEditResponse,

    /**
     * The CreateEditResponseChoices model constructor.
     * @property {module:model/CreateEditResponseChoices}
     */
    CreateEditResponseChoices,

    /**
     * The CreateEmbeddingRequest model constructor.
     * @property {module:model/CreateEmbeddingRequest}
     */
    CreateEmbeddingRequest,

    /**
     * The CreateEmbeddingResponse model constructor.
     * @property {module:model/CreateEmbeddingResponse}
     */
    CreateEmbeddingResponse,

    /**
     * The CreateEmbeddingResponseUsage model constructor.
     * @property {module:model/CreateEmbeddingResponseUsage}
     */
    CreateEmbeddingResponseUsage,

    /**
     * The CreateFileRequest model constructor.
     * @property {module:model/CreateFileRequest}
     */
    CreateFileRequest,

    /**
     * The CreateFineTuneRequest model constructor.
     * @property {module:model/CreateFineTuneRequest}
     */
    CreateFineTuneRequest,

    /**
     * The CreateFineTuneRequestHyperparameters model constructor.
     * @property {module:model/CreateFineTuneRequestHyperparameters}
     */
    CreateFineTuneRequestHyperparameters,

    /**
     * The CreateFineTuningJobRequest model constructor.
     * @property {module:model/CreateFineTuningJobRequest}
     */
    CreateFineTuningJobRequest,

    /**
     * The CreateFineTuningJobRequestHyperparameters model constructor.
     * @property {module:model/CreateFineTuningJobRequestHyperparameters}
     */
    CreateFineTuningJobRequestHyperparameters,

    /**
     * The CreateImageEditRequest model constructor.
     * @property {module:model/CreateImageEditRequest}
     */
    CreateImageEditRequest,

    /**
     * The CreateImageRequest model constructor.
     * @property {module:model/CreateImageRequest}
     */
    CreateImageRequest,

    /**
     * The CreateImageVariationRequest model constructor.
     * @property {module:model/CreateImageVariationRequest}
     */
    CreateImageVariationRequest,

    /**
     * The CreateMessageRequest model constructor.
     * @property {module:model/CreateMessageRequest}
     */
    CreateMessageRequest,

    /**
     * The CreateModerationRequest model constructor.
     * @property {module:model/CreateModerationRequest}
     */
    CreateModerationRequest,

    /**
     * The CreateModerationResponse model constructor.
     * @property {module:model/CreateModerationResponse}
     */
    CreateModerationResponse,

    /**
     * The CreateModerationResponseCategories model constructor.
     * @property {module:model/CreateModerationResponseCategories}
     */
    CreateModerationResponseCategories,

    /**
     * The CreateModerationResponseCategoryScores model constructor.
     * @property {module:model/CreateModerationResponseCategoryScores}
     */
    CreateModerationResponseCategoryScores,

    /**
     * The CreateModerationResponseResults model constructor.
     * @property {module:model/CreateModerationResponseResults}
     */
    CreateModerationResponseResults,

    /**
     * The CreateRunRequest model constructor.
     * @property {module:model/CreateRunRequest}
     */
    CreateRunRequest,

    /**
     * The CreateSpeechRequest model constructor.
     * @property {module:model/CreateSpeechRequest}
     */
    CreateSpeechRequest,

    /**
     * The CreateThreadAndRunRequest model constructor.
     * @property {module:model/CreateThreadAndRunRequest}
     */
    CreateThreadAndRunRequest,

    /**
     * The CreateThreadRequest model constructor.
     * @property {module:model/CreateThreadRequest}
     */
    CreateThreadRequest,

    /**
     * The CreateTranscriptionRequest model constructor.
     * @property {module:model/CreateTranscriptionRequest}
     */
    CreateTranscriptionRequest,

    /**
     * The CreateTranscriptionResponse model constructor.
     * @property {module:model/CreateTranscriptionResponse}
     */
    CreateTranscriptionResponse,

    /**
     * The CreateTranslationRequest model constructor.
     * @property {module:model/CreateTranslationRequest}
     */
    CreateTranslationRequest,

    /**
     * The CreateTranslationResponse model constructor.
     * @property {module:model/CreateTranslationResponse}
     */
    CreateTranslationResponse,

    /**
     * The DeleteAssistantFileResponse model constructor.
     * @property {module:model/DeleteAssistantFileResponse}
     */
    DeleteAssistantFileResponse,

    /**
     * The DeleteAssistantResponse model constructor.
     * @property {module:model/DeleteAssistantResponse}
     */
    DeleteAssistantResponse,

    /**
     * The DeleteFileResponse model constructor.
     * @property {module:model/DeleteFileResponse}
     */
    DeleteFileResponse,

    /**
     * The DeleteMessageResponse model constructor.
     * @property {module:model/DeleteMessageResponse}
     */
    DeleteMessageResponse,

    /**
     * The DeleteModelResponse model constructor.
     * @property {module:model/DeleteModelResponse}
     */
    DeleteModelResponse,

    /**
     * The DeleteThreadResponse model constructor.
     * @property {module:model/DeleteThreadResponse}
     */
    DeleteThreadResponse,

    /**
     * The Embedding model constructor.
     * @property {module:model/Embedding}
     */
    Embedding,

    /**
     * The Error model constructor.
     * @property {module:model/Error}
     */
    Error,

    /**
     * The ErrorResponse model constructor.
     * @property {module:model/ErrorResponse}
     */
    ErrorResponse,

    /**
     * The FineTune model constructor.
     * @property {module:model/FineTune}
     */
    FineTune,

    /**
     * The FineTuneEvent model constructor.
     * @property {module:model/FineTuneEvent}
     */
    FineTuneEvent,

    /**
     * The FineTuneHyperparams model constructor.
     * @property {module:model/FineTuneHyperparams}
     */
    FineTuneHyperparams,

    /**
     * The FineTuningJob model constructor.
     * @property {module:model/FineTuningJob}
     */
    FineTuningJob,

    /**
     * The FineTuningJobError model constructor.
     * @property {module:model/FineTuningJobError}
     */
    FineTuningJobError,

    /**
     * The FineTuningJobEvent model constructor.
     * @property {module:model/FineTuningJobEvent}
     */
    FineTuningJobEvent,

    /**
     * The FineTuningJobHyperparameters model constructor.
     * @property {module:model/FineTuningJobHyperparameters}
     */
    FineTuningJobHyperparameters,

    /**
     * The Image model constructor.
     * @property {module:model/Image}
     */
    Image,

    /**
     * The ImagesResponse model constructor.
     * @property {module:model/ImagesResponse}
     */
    ImagesResponse,

    /**
     * The ListAssistantFilesResponse model constructor.
     * @property {module:model/ListAssistantFilesResponse}
     */
    ListAssistantFilesResponse,

    /**
     * The ListAssistantsResponse model constructor.
     * @property {module:model/ListAssistantsResponse}
     */
    ListAssistantsResponse,

    /**
     * The ListFilesResponse model constructor.
     * @property {module:model/ListFilesResponse}
     */
    ListFilesResponse,

    /**
     * The ListFineTuneEventsResponse model constructor.
     * @property {module:model/ListFineTuneEventsResponse}
     */
    ListFineTuneEventsResponse,

    /**
     * The ListFineTunesResponse model constructor.
     * @property {module:model/ListFineTunesResponse}
     */
    ListFineTunesResponse,

    /**
     * The ListFineTuningJobEventsResponse model constructor.
     * @property {module:model/ListFineTuningJobEventsResponse}
     */
    ListFineTuningJobEventsResponse,

    /**
     * The ListMessageFilesResponse model constructor.
     * @property {module:model/ListMessageFilesResponse}
     */
    ListMessageFilesResponse,

    /**
     * The ListMessagesResponse model constructor.
     * @property {module:model/ListMessagesResponse}
     */
    ListMessagesResponse,

    /**
     * The ListModelsResponse model constructor.
     * @property {module:model/ListModelsResponse}
     */
    ListModelsResponse,

    /**
     * The ListPaginatedFineTuningJobsResponse model constructor.
     * @property {module:model/ListPaginatedFineTuningJobsResponse}
     */
    ListPaginatedFineTuningJobsResponse,

    /**
     * The ListRunStepsResponse model constructor.
     * @property {module:model/ListRunStepsResponse}
     */
    ListRunStepsResponse,

    /**
     * The ListRunsResponse model constructor.
     * @property {module:model/ListRunsResponse}
     */
    ListRunsResponse,

    /**
     * The ListThreadsResponse model constructor.
     * @property {module:model/ListThreadsResponse}
     */
    ListThreadsResponse,

    /**
     * The MessageContentImageFileObject model constructor.
     * @property {module:model/MessageContentImageFileObject}
     */
    MessageContentImageFileObject,

    /**
     * The MessageContentImageFileObjectImageFile model constructor.
     * @property {module:model/MessageContentImageFileObjectImageFile}
     */
    MessageContentImageFileObjectImageFile,

    /**
     * The MessageContentTextAnnotationsFileCitationObject model constructor.
     * @property {module:model/MessageContentTextAnnotationsFileCitationObject}
     */
    MessageContentTextAnnotationsFileCitationObject,

    /**
     * The MessageContentTextAnnotationsFileCitationObjectFileCitation model constructor.
     * @property {module:model/MessageContentTextAnnotationsFileCitationObjectFileCitation}
     */
    MessageContentTextAnnotationsFileCitationObjectFileCitation,

    /**
     * The MessageContentTextAnnotationsFilePathObject model constructor.
     * @property {module:model/MessageContentTextAnnotationsFilePathObject}
     */
    MessageContentTextAnnotationsFilePathObject,

    /**
     * The MessageContentTextAnnotationsFilePathObjectFilePath model constructor.
     * @property {module:model/MessageContentTextAnnotationsFilePathObjectFilePath}
     */
    MessageContentTextAnnotationsFilePathObjectFilePath,

    /**
     * The MessageContentTextObject model constructor.
     * @property {module:model/MessageContentTextObject}
     */
    MessageContentTextObject,

    /**
     * The MessageContentTextObjectText model constructor.
     * @property {module:model/MessageContentTextObjectText}
     */
    MessageContentTextObjectText,

    /**
     * The MessageFileObject model constructor.
     * @property {module:model/MessageFileObject}
     */
    MessageFileObject,

    /**
     * The MessageObject model constructor.
     * @property {module:model/MessageObject}
     */
    MessageObject,

    /**
     * The Model model constructor.
     * @property {module:model/Model}
     */
    Model,

    /**
     * The ModifyAssistantRequest model constructor.
     * @property {module:model/ModifyAssistantRequest}
     */
    ModifyAssistantRequest,

    /**
     * The ModifyMessageRequest model constructor.
     * @property {module:model/ModifyMessageRequest}
     */
    ModifyMessageRequest,

    /**
     * The ModifyRunRequest model constructor.
     * @property {module:model/ModifyRunRequest}
     */
    ModifyRunRequest,

    /**
     * The ModifyThreadRequest model constructor.
     * @property {module:model/ModifyThreadRequest}
     */
    ModifyThreadRequest,

    /**
     * The OneOfAssistantObjectToolsItems model constructor.
     * @property {module:model/OneOfAssistantObjectToolsItems}
     */
    OneOfAssistantObjectToolsItems,

    /**
     * The OneOfChatCompletionRequestUserMessageContent model constructor.
     * @property {module:model/OneOfChatCompletionRequestUserMessageContent}
     */
    OneOfChatCompletionRequestUserMessageContent,

    /**
     * The OneOfCreateAssistantRequestToolsItems model constructor.
     * @property {module:model/OneOfCreateAssistantRequestToolsItems}
     */
    OneOfCreateAssistantRequestToolsItems,

    /**
     * The OneOfCreateChatCompletionRequestFunctionCall model constructor.
     * @property {module:model/OneOfCreateChatCompletionRequestFunctionCall}
     */
    OneOfCreateChatCompletionRequestFunctionCall,

    /**
     * The OneOfCreateChatCompletionRequestStop model constructor.
     * @property {module:model/OneOfCreateChatCompletionRequestStop}
     */
    OneOfCreateChatCompletionRequestStop,

    /**
     * The OneOfCreateCompletionRequestPrompt model constructor.
     * @property {module:model/OneOfCreateCompletionRequestPrompt}
     */
    OneOfCreateCompletionRequestPrompt,

    /**
     * The OneOfCreateCompletionRequestStop model constructor.
     * @property {module:model/OneOfCreateCompletionRequestStop}
     */
    OneOfCreateCompletionRequestStop,

    /**
     * The OneOfCreateEmbeddingRequestInput model constructor.
     * @property {module:model/OneOfCreateEmbeddingRequestInput}
     */
    OneOfCreateEmbeddingRequestInput,

    /**
     * The OneOfCreateFineTuneRequestHyperparametersNEpochs model constructor.
     * @property {module:model/OneOfCreateFineTuneRequestHyperparametersNEpochs}
     */
    OneOfCreateFineTuneRequestHyperparametersNEpochs,

    /**
     * The OneOfCreateFineTuningJobRequestHyperparametersBatchSize model constructor.
     * @property {module:model/OneOfCreateFineTuningJobRequestHyperparametersBatchSize}
     */
    OneOfCreateFineTuningJobRequestHyperparametersBatchSize,

    /**
     * The OneOfCreateFineTuningJobRequestHyperparametersLearningRateMultiplier model constructor.
     * @property {module:model/OneOfCreateFineTuningJobRequestHyperparametersLearningRateMultiplier}
     */
    OneOfCreateFineTuningJobRequestHyperparametersLearningRateMultiplier,

    /**
     * The OneOfCreateFineTuningJobRequestHyperparametersNEpochs model constructor.
     * @property {module:model/OneOfCreateFineTuningJobRequestHyperparametersNEpochs}
     */
    OneOfCreateFineTuningJobRequestHyperparametersNEpochs,

    /**
     * The OneOfCreateModerationRequestInput model constructor.
     * @property {module:model/OneOfCreateModerationRequestInput}
     */
    OneOfCreateModerationRequestInput,

    /**
     * The OneOfCreateRunRequestToolsItems model constructor.
     * @property {module:model/OneOfCreateRunRequestToolsItems}
     */
    OneOfCreateRunRequestToolsItems,

    /**
     * The OneOfCreateThreadAndRunRequestToolsItems model constructor.
     * @property {module:model/OneOfCreateThreadAndRunRequestToolsItems}
     */
    OneOfCreateThreadAndRunRequestToolsItems,

    /**
     * The OneOfFineTuningJobHyperparametersNEpochs model constructor.
     * @property {module:model/OneOfFineTuningJobHyperparametersNEpochs}
     */
    OneOfFineTuningJobHyperparametersNEpochs,

    /**
     * The OneOfMessageContentTextObjectTextAnnotationsItems model constructor.
     * @property {module:model/OneOfMessageContentTextObjectTextAnnotationsItems}
     */
    OneOfMessageContentTextObjectTextAnnotationsItems,

    /**
     * The OneOfMessageObjectContentItems model constructor.
     * @property {module:model/OneOfMessageObjectContentItems}
     */
    OneOfMessageObjectContentItems,

    /**
     * The OneOfModifyAssistantRequestToolsItems model constructor.
     * @property {module:model/OneOfModifyAssistantRequestToolsItems}
     */
    OneOfModifyAssistantRequestToolsItems,

    /**
     * The OneOfRunObjectToolsItems model constructor.
     * @property {module:model/OneOfRunObjectToolsItems}
     */
    OneOfRunObjectToolsItems,

    /**
     * The OneOfRunStepDetailsToolCallsCodeObjectCodeInterpreterOutputsItems model constructor.
     * @property {module:model/OneOfRunStepDetailsToolCallsCodeObjectCodeInterpreterOutputsItems}
     */
    OneOfRunStepDetailsToolCallsCodeObjectCodeInterpreterOutputsItems,

    /**
     * The OneOfRunStepDetailsToolCallsObjectToolCallsItems model constructor.
     * @property {module:model/OneOfRunStepDetailsToolCallsObjectToolCallsItems}
     */
    OneOfRunStepDetailsToolCallsObjectToolCallsItems,

    /**
     * The OneOfRunStepObjectStepDetails model constructor.
     * @property {module:model/OneOfRunStepObjectStepDetails}
     */
    OneOfRunStepObjectStepDetails,

    /**
     * The OpenAIFile model constructor.
     * @property {module:model/OpenAIFile}
     */
    OpenAIFile,

    /**
     * The RunObject model constructor.
     * @property {module:model/RunObject}
     */
    RunObject,

    /**
     * The RunObjectLastError model constructor.
     * @property {module:model/RunObjectLastError}
     */
    RunObjectLastError,

    /**
     * The RunObjectRequiredAction model constructor.
     * @property {module:model/RunObjectRequiredAction}
     */
    RunObjectRequiredAction,

    /**
     * The RunObjectRequiredActionSubmitToolOutputs model constructor.
     * @property {module:model/RunObjectRequiredActionSubmitToolOutputs}
     */
    RunObjectRequiredActionSubmitToolOutputs,

    /**
     * The RunStepDetailsMessageCreationObject model constructor.
     * @property {module:model/RunStepDetailsMessageCreationObject}
     */
    RunStepDetailsMessageCreationObject,

    /**
     * The RunStepDetailsMessageCreationObjectMessageCreation model constructor.
     * @property {module:model/RunStepDetailsMessageCreationObjectMessageCreation}
     */
    RunStepDetailsMessageCreationObjectMessageCreation,

    /**
     * The RunStepDetailsToolCallsCodeObject model constructor.
     * @property {module:model/RunStepDetailsToolCallsCodeObject}
     */
    RunStepDetailsToolCallsCodeObject,

    /**
     * The RunStepDetailsToolCallsCodeObjectCodeInterpreter model constructor.
     * @property {module:model/RunStepDetailsToolCallsCodeObjectCodeInterpreter}
     */
    RunStepDetailsToolCallsCodeObjectCodeInterpreter,

    /**
     * The RunStepDetailsToolCallsCodeOutputImageObject model constructor.
     * @property {module:model/RunStepDetailsToolCallsCodeOutputImageObject}
     */
    RunStepDetailsToolCallsCodeOutputImageObject,

    /**
     * The RunStepDetailsToolCallsCodeOutputImageObjectImage model constructor.
     * @property {module:model/RunStepDetailsToolCallsCodeOutputImageObjectImage}
     */
    RunStepDetailsToolCallsCodeOutputImageObjectImage,

    /**
     * The RunStepDetailsToolCallsCodeOutputLogsObject model constructor.
     * @property {module:model/RunStepDetailsToolCallsCodeOutputLogsObject}
     */
    RunStepDetailsToolCallsCodeOutputLogsObject,

    /**
     * The RunStepDetailsToolCallsFunctionObject model constructor.
     * @property {module:model/RunStepDetailsToolCallsFunctionObject}
     */
    RunStepDetailsToolCallsFunctionObject,

    /**
     * The RunStepDetailsToolCallsFunctionObjectFunction model constructor.
     * @property {module:model/RunStepDetailsToolCallsFunctionObjectFunction}
     */
    RunStepDetailsToolCallsFunctionObjectFunction,

    /**
     * The RunStepDetailsToolCallsObject model constructor.
     * @property {module:model/RunStepDetailsToolCallsObject}
     */
    RunStepDetailsToolCallsObject,

    /**
     * The RunStepDetailsToolCallsRetrievalObject model constructor.
     * @property {module:model/RunStepDetailsToolCallsRetrievalObject}
     */
    RunStepDetailsToolCallsRetrievalObject,

    /**
     * The RunStepObject model constructor.
     * @property {module:model/RunStepObject}
     */
    RunStepObject,

    /**
     * The RunStepObjectLastError model constructor.
     * @property {module:model/RunStepObjectLastError}
     */
    RunStepObjectLastError,

    /**
     * The RunToolCallObject model constructor.
     * @property {module:model/RunToolCallObject}
     */
    RunToolCallObject,

    /**
     * The RunToolCallObjectFunction model constructor.
     * @property {module:model/RunToolCallObjectFunction}
     */
    RunToolCallObjectFunction,

    /**
     * The SubmitToolOutputsRunRequest model constructor.
     * @property {module:model/SubmitToolOutputsRunRequest}
     */
    SubmitToolOutputsRunRequest,

    /**
     * The SubmitToolOutputsRunRequestToolOutputs model constructor.
     * @property {module:model/SubmitToolOutputsRunRequestToolOutputs}
     */
    SubmitToolOutputsRunRequestToolOutputs,

    /**
     * The ThreadObject model constructor.
     * @property {module:model/ThreadObject}
     */
    ThreadObject,

    /**
    * The AssistantApi service constructor.
    * @property {module:api/AssistantApi}
    */
    AssistantApi,

    /**
    * The AssistantsApi service constructor.
    * @property {module:api/AssistantsApi}
    */
    AssistantsApi,

    /**
    * The AudioApi service constructor.
    * @property {module:api/AudioApi}
    */
    AudioApi,

    /**
    * The ChatApi service constructor.
    * @property {module:api/ChatApi}
    */
    ChatApi,

    /**
    * The CompletionsApi service constructor.
    * @property {module:api/CompletionsApi}
    */
    CompletionsApi,

    /**
    * The EditsApi service constructor.
    * @property {module:api/EditsApi}
    */
    EditsApi,

    /**
    * The EmbeddingsApi service constructor.
    * @property {module:api/EmbeddingsApi}
    */
    EmbeddingsApi,

    /**
    * The FilesApi service constructor.
    * @property {module:api/FilesApi}
    */
    FilesApi,

    /**
    * The FineTunesApi service constructor.
    * @property {module:api/FineTunesApi}
    */
    FineTunesApi,

    /**
    * The FineTuningApi service constructor.
    * @property {module:api/FineTuningApi}
    */
    FineTuningApi,

    /**
    * The ImagesApi service constructor.
    * @property {module:api/ImagesApi}
    */
    ImagesApi,

    /**
    * The ModelsApi service constructor.
    * @property {module:api/ModelsApi}
    */
    ModelsApi,

    /**
    * The ModerationsApi service constructor.
    * @property {module:api/ModerationsApi}
    */
    ModerationsApi
};
