/*
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.50
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The AssistantToolsCode model module.
 * @module model/AssistantToolsCode
 * @version 2.0.0
 */
export class AssistantToolsCode {
  /**
   * Constructs a new <code>AssistantToolsCode</code>.
   * @alias module:model/AssistantToolsCode
   * @class
   * @param type {module:model/AssistantToolsCode.TypeEnum} The type of tool being defined: `code_interpreter`
   */
  constructor(type) {
    this.type = type;
  }

  /**
   * Constructs a <code>AssistantToolsCode</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AssistantToolsCode} obj Optional instance to populate.
   * @return {module:model/AssistantToolsCode} The populated <code>AssistantToolsCode</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new AssistantToolsCode();
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'String');
    }
    return obj;
  }
}

/**
 * Allowed values for the <code>type</code> property.
 * @enum {String}
 * @readonly
 */
AssistantToolsCode.TypeEnum = {
  /**
   * value: "code_interpreter"
   * @const
   */
  codeInterpreter: "code_interpreter"
};
/**
 * The type of tool being defined: `code_interpreter`
 * @member {module:model/AssistantToolsCode.TypeEnum} type
 */
AssistantToolsCode.prototype.type = undefined;

// Implement OneOfAssistantObjectToolsItems interface:
// Implement OneOfCreateAssistantRequestToolsItems interface:
// Implement OneOfCreateRunRequestToolsItems interface:
// Implement OneOfCreateThreadAndRunRequestToolsItems interface:
// Implement OneOfModifyAssistantRequestToolsItems interface:
// Implement OneOfRunObjectToolsItems interface:
