/*
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.50
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The AssistantFileObject model module.
 * @module model/AssistantFileObject
 * @version 2.0.0
 */
export class AssistantFileObject {
  /**
   * Constructs a new <code>AssistantFileObject</code>.
   * A list of [Files](/docs/api-reference/files) attached to an &#x60;assistant&#x60;.
   * @alias module:model/AssistantFileObject
   * @class
   * @param id {String} The identifier, which can be referenced in API endpoints.
   * @param _object {module:model/AssistantFileObject.ObjectEnum} The object type, which is always `assistant.file`.
   * @param createdAt {Number} The Unix timestamp (in seconds) for when the assistant file was created.
   * @param assistantId {String} The assistant ID that the file is attached to.
   */
  constructor(id, _object, createdAt, assistantId) {
    this.id = id;
    this._object = _object;
    this.createdAt = createdAt;
    this.assistantId = assistantId;
  }

  /**
   * Constructs a <code>AssistantFileObject</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AssistantFileObject} obj Optional instance to populate.
   * @return {module:model/AssistantFileObject} The populated <code>AssistantFileObject</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new AssistantFileObject();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('object'))
        obj._object = ApiClient.convertToType(data['object'], 'String');
      if (data.hasOwnProperty('created_at'))
        obj.createdAt = ApiClient.convertToType(data['created_at'], 'Number');
      if (data.hasOwnProperty('assistant_id'))
        obj.assistantId = ApiClient.convertToType(data['assistant_id'], 'String');
    }
    return obj;
  }
}

/**
 * The identifier, which can be referenced in API endpoints.
 * @member {String} id
 */
AssistantFileObject.prototype.id = undefined;

/**
 * Allowed values for the <code>_object</code> property.
 * @enum {String}
 * @readonly
 */
AssistantFileObject.ObjectEnum = {
  /**
   * value: "assistant.file"
   * @const
   */
  assistantFile: "assistant.file"
};
/**
 * The object type, which is always `assistant.file`.
 * @member {module:model/AssistantFileObject.ObjectEnum} _object
 */
AssistantFileObject.prototype._object = undefined;

/**
 * The Unix timestamp (in seconds) for when the assistant file was created.
 * @member {Number} createdAt
 */
AssistantFileObject.prototype.createdAt = undefined;

/**
 * The assistant ID that the file is attached to.
 * @member {String} assistantId
 */
AssistantFileObject.prototype.assistantId = undefined;

