/*
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.50
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {ChatCompletionNamedToolChoiceFunction} from './ChatCompletionNamedToolChoiceFunction';

/**
 * The ChatCompletionNamedToolChoice model module.
 * @module model/ChatCompletionNamedToolChoice
 * @version 2.0.0
 */
export class ChatCompletionNamedToolChoice {
  /**
   * Constructs a new <code>ChatCompletionNamedToolChoice</code>.
   * Specifies a tool the model should use. Use to force the model to call a specific function.
   * @alias module:model/ChatCompletionNamedToolChoice
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ChatCompletionNamedToolChoice</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ChatCompletionNamedToolChoice} obj Optional instance to populate.
   * @return {module:model/ChatCompletionNamedToolChoice} The populated <code>ChatCompletionNamedToolChoice</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ChatCompletionNamedToolChoice();
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'String');
      if (data.hasOwnProperty('function'))
        obj._function = ChatCompletionNamedToolChoiceFunction.constructFromObject(data['function']);
    }
    return obj;
  }
}

/**
 * Allowed values for the <code>type</code> property.
 * @enum {String}
 * @readonly
 */
ChatCompletionNamedToolChoice.TypeEnum = {
  /**
   * value: "function"
   * @const
   */
  _function: "function"
};
/**
 * The type of the tool. Currently, only `function` is supported.
 * @member {module:model/ChatCompletionNamedToolChoice.TypeEnum} type
 */
ChatCompletionNamedToolChoice.prototype.type = undefined;

/**
 * @member {module:model/ChatCompletionNamedToolChoiceFunction} _function
 */
ChatCompletionNamedToolChoice.prototype._function = undefined;

// Implement ChatCompletionToolChoiceOption interface:
