/*
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.50
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {ChatCompletionRequestMessageContentPartImageImageUrl} from './ChatCompletionRequestMessageContentPartImageImageUrl';

/**
 * The ChatCompletionRequestMessageContentPartImage model module.
 * @module model/ChatCompletionRequestMessageContentPartImage
 * @version 2.0.0
 */
export class ChatCompletionRequestMessageContentPartImage {
  /**
   * Constructs a new <code>ChatCompletionRequestMessageContentPartImage</code>.
   * @alias module:model/ChatCompletionRequestMessageContentPartImage
   * @class
   * @param type {module:model/ChatCompletionRequestMessageContentPartImage.TypeEnum} The type of the content part.
   * @param imageUrl {module:model/ChatCompletionRequestMessageContentPartImageImageUrl} 
   */
  constructor(type, imageUrl) {
    this.type = type;
    this.imageUrl = imageUrl;
  }

  /**
   * Constructs a <code>ChatCompletionRequestMessageContentPartImage</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ChatCompletionRequestMessageContentPartImage} obj Optional instance to populate.
   * @return {module:model/ChatCompletionRequestMessageContentPartImage} The populated <code>ChatCompletionRequestMessageContentPartImage</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ChatCompletionRequestMessageContentPartImage();
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'String');
      if (data.hasOwnProperty('image_url'))
        obj.imageUrl = ChatCompletionRequestMessageContentPartImageImageUrl.constructFromObject(data['image_url']);
    }
    return obj;
  }
}

/**
 * Allowed values for the <code>type</code> property.
 * @enum {String}
 * @readonly
 */
ChatCompletionRequestMessageContentPartImage.TypeEnum = {
  /**
   * value: "image_url"
   * @const
   */
  imageUrl: "image_url"
};
/**
 * The type of the content part.
 * @member {module:model/ChatCompletionRequestMessageContentPartImage.TypeEnum} type
 */
ChatCompletionRequestMessageContentPartImage.prototype.type = undefined;

/**
 * @member {module:model/ChatCompletionRequestMessageContentPartImageImageUrl} imageUrl
 */
ChatCompletionRequestMessageContentPartImage.prototype.imageUrl = undefined;

// Implement ChatCompletionRequestMessageContentPart interface:
