/*
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.50
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {ChatCompletionMessageToolCalls} from './ChatCompletionMessageToolCalls';
import {ChatCompletionRequestAssistantMessageFunctionCall} from './ChatCompletionRequestAssistantMessageFunctionCall';

/**
 * The ChatCompletionResponseMessage model module.
 * @module model/ChatCompletionResponseMessage
 * @version 2.0.0
 */
export class ChatCompletionResponseMessage {
  /**
   * Constructs a new <code>ChatCompletionResponseMessage</code>.
   * A chat completion message generated by the model.
   * @alias module:model/ChatCompletionResponseMessage
   * @class
   * @param content {String} The contents of the message.
   * @param role {module:model/ChatCompletionResponseMessage.RoleEnum} The role of the author of this message.
   */
  constructor(content, role) {
    this.content = content;
    this.role = role;
  }

  /**
   * Constructs a <code>ChatCompletionResponseMessage</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ChatCompletionResponseMessage} obj Optional instance to populate.
   * @return {module:model/ChatCompletionResponseMessage} The populated <code>ChatCompletionResponseMessage</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ChatCompletionResponseMessage();
      if (data.hasOwnProperty('content'))
        obj.content = ApiClient.convertToType(data['content'], 'String');
      if (data.hasOwnProperty('tool_calls'))
        obj.toolCalls = ChatCompletionMessageToolCalls.constructFromObject(data['tool_calls']);
      if (data.hasOwnProperty('role'))
        obj.role = ApiClient.convertToType(data['role'], 'String');
      if (data.hasOwnProperty('function_call'))
        obj.functionCall = ChatCompletionRequestAssistantMessageFunctionCall.constructFromObject(data['function_call']);
    }
    return obj;
  }
}

/**
 * The contents of the message.
 * @member {String} content
 */
ChatCompletionResponseMessage.prototype.content = undefined;

/**
 * @member {module:model/ChatCompletionMessageToolCalls} toolCalls
 */
ChatCompletionResponseMessage.prototype.toolCalls = undefined;

/**
 * Allowed values for the <code>role</code> property.
 * @enum {String}
 * @readonly
 */
ChatCompletionResponseMessage.RoleEnum = {
  /**
   * value: "assistant"
   * @const
   */
  assistant: "assistant"
};
/**
 * The role of the author of this message.
 * @member {module:model/ChatCompletionResponseMessage.RoleEnum} role
 */
ChatCompletionResponseMessage.prototype.role = undefined;

/**
 * @member {module:model/ChatCompletionRequestAssistantMessageFunctionCall} functionCall
 */
ChatCompletionResponseMessage.prototype.functionCall = undefined;

