/*
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.50
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The ChatCompletionMessageToolCallFunction model module.
 * @module model/ChatCompletionMessageToolCallFunction
 * @version 2.0.0
 */
export class ChatCompletionMessageToolCallFunction {
  /**
   * Constructs a new <code>ChatCompletionMessageToolCallFunction</code>.
   * The function that the model called.
   * @alias module:model/ChatCompletionMessageToolCallFunction
   * @class
   * @param name {String} The name of the function to call.
   * @param _arguments {String} The arguments to call the function with, as generated by the model in JSON format. Note that the model does not always generate valid JSON, and may hallucinate parameters not defined by your function schema. Validate the arguments in your code before calling your function.
   */
  constructor(name, _arguments) {
    this.name = name;
    this._arguments = _arguments;
  }

  /**
   * Constructs a <code>ChatCompletionMessageToolCallFunction</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ChatCompletionMessageToolCallFunction} obj Optional instance to populate.
   * @return {module:model/ChatCompletionMessageToolCallFunction} The populated <code>ChatCompletionMessageToolCallFunction</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ChatCompletionMessageToolCallFunction();
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('arguments'))
        obj._arguments = ApiClient.convertToType(data['arguments'], 'String');
    }
    return obj;
  }
}

/**
 * The name of the function to call.
 * @member {String} name
 */
ChatCompletionMessageToolCallFunction.prototype.name = undefined;

/**
 * The arguments to call the function with, as generated by the model in JSON format. Note that the model does not always generate valid JSON, and may hallucinate parameters not defined by your function schema. Validate the arguments in your code before calling your function.
 * @member {String} _arguments
 */
ChatCompletionMessageToolCallFunction.prototype._arguments = undefined;

