/*
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.50
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The CreateSpeechRequest model module.
 * @module model/CreateSpeechRequest
 * @version 2.0.0
 */
export class CreateSpeechRequest {
  /**
   * Constructs a new <code>CreateSpeechRequest</code>.
   * @alias module:model/CreateSpeechRequest
   * @class
   * @param model {Object} One of the available [TTS models](/docs/models/tts): `tts-1` or `tts-1-hd` 
   * @param input {String} The text to generate audio for. The maximum length is 4096 characters.
   * @param voice {module:model/CreateSpeechRequest.VoiceEnum} The voice to use when generating the audio. Supported voices are `alloy`, `echo`, `fable`, `onyx`, `nova`, and `shimmer`.
   */
  constructor(model, input, voice) {
    this.model = model;
    this.input = input;
    this.voice = voice;
  }

  /**
   * Constructs a <code>CreateSpeechRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CreateSpeechRequest} obj Optional instance to populate.
   * @return {module:model/CreateSpeechRequest} The populated <code>CreateSpeechRequest</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CreateSpeechRequest();
      if (data.hasOwnProperty('model'))
        obj.model = ApiClient.convertToType(data['model'], Object);
      if (data.hasOwnProperty('input'))
        obj.input = ApiClient.convertToType(data['input'], 'String');
      if (data.hasOwnProperty('voice'))
        obj.voice = ApiClient.convertToType(data['voice'], 'String');
      if (data.hasOwnProperty('response_format'))
        obj.responseFormat = ApiClient.convertToType(data['response_format'], 'String');
      if (data.hasOwnProperty('speed'))
        obj.speed = ApiClient.convertToType(data['speed'], 'Number');
    }
    return obj;
  }
}

/**
 * One of the available [TTS models](/docs/models/tts): `tts-1` or `tts-1-hd` 
 * @member {Object} model
 */
CreateSpeechRequest.prototype.model = undefined;

/**
 * The text to generate audio for. The maximum length is 4096 characters.
 * @member {String} input
 */
CreateSpeechRequest.prototype.input = undefined;

/**
 * Allowed values for the <code>voice</code> property.
 * @enum {String}
 * @readonly
 */
CreateSpeechRequest.VoiceEnum = {
  /**
   * value: "alloy"
   * @const
   */
  alloy: "alloy",

  /**
   * value: "echo"
   * @const
   */
  echo: "echo",

  /**
   * value: "fable"
   * @const
   */
  fable: "fable",

  /**
   * value: "onyx"
   * @const
   */
  onyx: "onyx",

  /**
   * value: "nova"
   * @const
   */
  nova: "nova",

  /**
   * value: "shimmer"
   * @const
   */
  shimmer: "shimmer"
};
/**
 * The voice to use when generating the audio. Supported voices are `alloy`, `echo`, `fable`, `onyx`, `nova`, and `shimmer`.
 * @member {module:model/CreateSpeechRequest.VoiceEnum} voice
 */
CreateSpeechRequest.prototype.voice = undefined;

/**
 * Allowed values for the <code>responseFormat</code> property.
 * @enum {String}
 * @readonly
 */
CreateSpeechRequest.ResponseFormatEnum = {
  /**
   * value: "mp3"
   * @const
   */
  mp3: "mp3",

  /**
   * value: "opus"
   * @const
   */
  opus: "opus",

  /**
   * value: "aac"
   * @const
   */
  aac: "aac",

  /**
   * value: "flac"
   * @const
   */
  flac: "flac"
};
/**
 * The format to audio in. Supported formats are `mp3`, `opus`, `aac`, and `flac`.
 * @member {module:model/CreateSpeechRequest.ResponseFormatEnum} responseFormat
 * @default 'mp3'
 */
CreateSpeechRequest.prototype.responseFormat = 'mp3';

/**
 * The speed of the generated audio. Select a value from `0.25` to `4.0`. `1.0` is the default.
 * @member {Number} speed
 * @default 1
 */
CreateSpeechRequest.prototype.speed = 1;

