/*
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.50
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {CompletionUsage} from './CompletionUsage';
import {CreateCompletionResponseChoices} from './CreateCompletionResponseChoices';

/**
 * The CreateCompletionResponse model module.
 * @module model/CreateCompletionResponse
 * @version 2.0.0
 */
export class CreateCompletionResponse {
  /**
   * Constructs a new <code>CreateCompletionResponse</code>.
   * Represents a completion response from the API. Note: both the streamed and non-streamed response objects share the same shape (unlike the chat endpoint). 
   * @alias module:model/CreateCompletionResponse
   * @class
   * @param id {String} A unique identifier for the completion.
   * @param choices {Array.<module:model/CreateCompletionResponseChoices>} The list of completion choices the model generated for the input prompt.
   * @param created {Number} The Unix timestamp (in seconds) of when the completion was created.
   * @param model {String} The model used for completion.
   * @param _object {module:model/CreateCompletionResponse.ObjectEnum} The object type, which is always \"text_completion\"
   */
  constructor(id, choices, created, model, _object) {
    this.id = id;
    this.choices = choices;
    this.created = created;
    this.model = model;
    this._object = _object;
  }

  /**
   * Constructs a <code>CreateCompletionResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CreateCompletionResponse} obj Optional instance to populate.
   * @return {module:model/CreateCompletionResponse} The populated <code>CreateCompletionResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CreateCompletionResponse();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('choices'))
        obj.choices = ApiClient.convertToType(data['choices'], [CreateCompletionResponseChoices]);
      if (data.hasOwnProperty('created'))
        obj.created = ApiClient.convertToType(data['created'], 'Number');
      if (data.hasOwnProperty('model'))
        obj.model = ApiClient.convertToType(data['model'], 'String');
      if (data.hasOwnProperty('system_fingerprint'))
        obj.systemFingerprint = ApiClient.convertToType(data['system_fingerprint'], 'String');
      if (data.hasOwnProperty('object'))
        obj._object = ApiClient.convertToType(data['object'], 'String');
      if (data.hasOwnProperty('usage'))
        obj.usage = CompletionUsage.constructFromObject(data['usage']);
    }
    return obj;
  }
}

/**
 * A unique identifier for the completion.
 * @member {String} id
 */
CreateCompletionResponse.prototype.id = undefined;

/**
 * The list of completion choices the model generated for the input prompt.
 * @member {Array.<module:model/CreateCompletionResponseChoices>} choices
 */
CreateCompletionResponse.prototype.choices = undefined;

/**
 * The Unix timestamp (in seconds) of when the completion was created.
 * @member {Number} created
 */
CreateCompletionResponse.prototype.created = undefined;

/**
 * The model used for completion.
 * @member {String} model
 */
CreateCompletionResponse.prototype.model = undefined;

/**
 * This fingerprint represents the backend configuration that the model runs with.  Can be used in conjunction with the `seed` request parameter to understand when backend changes have been made that might impact determinism. 
 * @member {String} systemFingerprint
 */
CreateCompletionResponse.prototype.systemFingerprint = undefined;

/**
 * Allowed values for the <code>_object</code> property.
 * @enum {String}
 * @readonly
 */
CreateCompletionResponse.ObjectEnum = {
  /**
   * value: "text_completion"
   * @const
   */
  textCompletion: "text_completion"
};
/**
 * The object type, which is always \"text_completion\"
 * @member {module:model/CreateCompletionResponse.ObjectEnum} _object
 */
CreateCompletionResponse.prototype._object = undefined;

/**
 * @member {module:model/CompletionUsage} usage
 */
CreateCompletionResponse.prototype.usage = undefined;

