/*
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.50
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The CreateModerationResponseCategoryScores model module.
 * @module model/CreateModerationResponseCategoryScores
 * @version 2.0.0
 */
export class CreateModerationResponseCategoryScores {
  /**
   * Constructs a new <code>CreateModerationResponseCategoryScores</code>.
   * A list of the categories along with their scores as predicted by model.
   * @alias module:model/CreateModerationResponseCategoryScores
   * @class
   * @param hate {Number} The score for the category 'hate'.
   * @param hatethreatening {Number} The score for the category 'hate/threatening'.
   * @param harassment {Number} The score for the category 'harassment'.
   * @param harassmentthreatening {Number} The score for the category 'harassment/threatening'.
   * @param selfHarm {Number} The score for the category 'self-harm'.
   * @param selfHarmintent {Number} The score for the category 'self-harm/intent'.
   * @param selfHarminstructions {Number} The score for the category 'self-harm/instructions'.
   * @param sexual {Number} The score for the category 'sexual'.
   * @param sexualminors {Number} The score for the category 'sexual/minors'.
   * @param violence {Number} The score for the category 'violence'.
   * @param violencegraphic {Number} The score for the category 'violence/graphic'.
   */
  constructor(hate, hatethreatening, harassment, harassmentthreatening, selfHarm, selfHarmintent, selfHarminstructions, sexual, sexualminors, violence, violencegraphic) {
    this.hate = hate;
    this.hatethreatening = hatethreatening;
    this.harassment = harassment;
    this.harassmentthreatening = harassmentthreatening;
    this.selfHarm = selfHarm;
    this.selfHarmintent = selfHarmintent;
    this.selfHarminstructions = selfHarminstructions;
    this.sexual = sexual;
    this.sexualminors = sexualminors;
    this.violence = violence;
    this.violencegraphic = violencegraphic;
  }

  /**
   * Constructs a <code>CreateModerationResponseCategoryScores</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CreateModerationResponseCategoryScores} obj Optional instance to populate.
   * @return {module:model/CreateModerationResponseCategoryScores} The populated <code>CreateModerationResponseCategoryScores</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CreateModerationResponseCategoryScores();
      if (data.hasOwnProperty('hate'))
        obj.hate = ApiClient.convertToType(data['hate'], 'Number');
      if (data.hasOwnProperty('hate/threatening'))
        obj.hatethreatening = ApiClient.convertToType(data['hate/threatening'], 'Number');
      if (data.hasOwnProperty('harassment'))
        obj.harassment = ApiClient.convertToType(data['harassment'], 'Number');
      if (data.hasOwnProperty('harassment/threatening'))
        obj.harassmentthreatening = ApiClient.convertToType(data['harassment/threatening'], 'Number');
      if (data.hasOwnProperty('self-harm'))
        obj.selfHarm = ApiClient.convertToType(data['self-harm'], 'Number');
      if (data.hasOwnProperty('self-harm/intent'))
        obj.selfHarmintent = ApiClient.convertToType(data['self-harm/intent'], 'Number');
      if (data.hasOwnProperty('self-harm/instructions'))
        obj.selfHarminstructions = ApiClient.convertToType(data['self-harm/instructions'], 'Number');
      if (data.hasOwnProperty('sexual'))
        obj.sexual = ApiClient.convertToType(data['sexual'], 'Number');
      if (data.hasOwnProperty('sexual/minors'))
        obj.sexualminors = ApiClient.convertToType(data['sexual/minors'], 'Number');
      if (data.hasOwnProperty('violence'))
        obj.violence = ApiClient.convertToType(data['violence'], 'Number');
      if (data.hasOwnProperty('violence/graphic'))
        obj.violencegraphic = ApiClient.convertToType(data['violence/graphic'], 'Number');
    }
    return obj;
  }
}

/**
 * The score for the category 'hate'.
 * @member {Number} hate
 */
CreateModerationResponseCategoryScores.prototype.hate = undefined;

/**
 * The score for the category 'hate/threatening'.
 * @member {Number} hatethreatening
 */
CreateModerationResponseCategoryScores.prototype.hatethreatening = undefined;

/**
 * The score for the category 'harassment'.
 * @member {Number} harassment
 */
CreateModerationResponseCategoryScores.prototype.harassment = undefined;

/**
 * The score for the category 'harassment/threatening'.
 * @member {Number} harassmentthreatening
 */
CreateModerationResponseCategoryScores.prototype.harassmentthreatening = undefined;

/**
 * The score for the category 'self-harm'.
 * @member {Number} selfHarm
 */
CreateModerationResponseCategoryScores.prototype.selfHarm = undefined;

/**
 * The score for the category 'self-harm/intent'.
 * @member {Number} selfHarmintent
 */
CreateModerationResponseCategoryScores.prototype.selfHarmintent = undefined;

/**
 * The score for the category 'self-harm/instructions'.
 * @member {Number} selfHarminstructions
 */
CreateModerationResponseCategoryScores.prototype.selfHarminstructions = undefined;

/**
 * The score for the category 'sexual'.
 * @member {Number} sexual
 */
CreateModerationResponseCategoryScores.prototype.sexual = undefined;

/**
 * The score for the category 'sexual/minors'.
 * @member {Number} sexualminors
 */
CreateModerationResponseCategoryScores.prototype.sexualminors = undefined;

/**
 * The score for the category 'violence'.
 * @member {Number} violence
 */
CreateModerationResponseCategoryScores.prototype.violence = undefined;

/**
 * The score for the category 'violence/graphic'.
 * @member {Number} violencegraphic
 */
CreateModerationResponseCategoryScores.prototype.violencegraphic = undefined;

