/*
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.50
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The CreateCompletionResponseLogprobs model module.
 * @module model/CreateCompletionResponseLogprobs
 * @version 2.0.0
 */
export class CreateCompletionResponseLogprobs {
  /**
   * Constructs a new <code>CreateCompletionResponseLogprobs</code>.
   * @alias module:model/CreateCompletionResponseLogprobs
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>CreateCompletionResponseLogprobs</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CreateCompletionResponseLogprobs} obj Optional instance to populate.
   * @return {module:model/CreateCompletionResponseLogprobs} The populated <code>CreateCompletionResponseLogprobs</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CreateCompletionResponseLogprobs();
      if (data.hasOwnProperty('text_offset'))
        obj.textOffset = ApiClient.convertToType(data['text_offset'], ['Number']);
      if (data.hasOwnProperty('token_logprobs'))
        obj.tokenLogprobs = ApiClient.convertToType(data['token_logprobs'], ['Number']);
      if (data.hasOwnProperty('tokens'))
        obj.tokens = ApiClient.convertToType(data['tokens'], ['String']);
      if (data.hasOwnProperty('top_logprobs'))
        obj.topLogprobs = ApiClient.convertToType(data['top_logprobs'], [{'String': 'Number'}]);
    }
    return obj;
  }
}

/**
 * @member {Array.<Number>} textOffset
 */
CreateCompletionResponseLogprobs.prototype.textOffset = undefined;

/**
 * @member {Array.<Number>} tokenLogprobs
 */
CreateCompletionResponseLogprobs.prototype.tokenLogprobs = undefined;

/**
 * @member {Array.<String>} tokens
 */
CreateCompletionResponseLogprobs.prototype.tokens = undefined;

/**
 * @member {Array.<Object.<String, Number>>} topLogprobs
 */
CreateCompletionResponseLogprobs.prototype.topLogprobs = undefined;

