/*
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.50
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {CreateModerationResponseCategories} from './CreateModerationResponseCategories';
import {CreateModerationResponseCategoryScores} from './CreateModerationResponseCategoryScores';

/**
 * The CreateModerationResponseResults model module.
 * @module model/CreateModerationResponseResults
 * @version 2.0.0
 */
export class CreateModerationResponseResults {
  /**
   * Constructs a new <code>CreateModerationResponseResults</code>.
   * @alias module:model/CreateModerationResponseResults
   * @class
   * @param flagged {Boolean} Whether the content violates [OpenAI's usage policies](/policies/usage-policies).
   * @param categories {module:model/CreateModerationResponseCategories} 
   * @param categoryScores {module:model/CreateModerationResponseCategoryScores} 
   */
  constructor(flagged, categories, categoryScores) {
    this.flagged = flagged;
    this.categories = categories;
    this.categoryScores = categoryScores;
  }

  /**
   * Constructs a <code>CreateModerationResponseResults</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CreateModerationResponseResults} obj Optional instance to populate.
   * @return {module:model/CreateModerationResponseResults} The populated <code>CreateModerationResponseResults</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CreateModerationResponseResults();
      if (data.hasOwnProperty('flagged'))
        obj.flagged = ApiClient.convertToType(data['flagged'], 'Boolean');
      if (data.hasOwnProperty('categories'))
        obj.categories = CreateModerationResponseCategories.constructFromObject(data['categories']);
      if (data.hasOwnProperty('category_scores'))
        obj.categoryScores = CreateModerationResponseCategoryScores.constructFromObject(data['category_scores']);
    }
    return obj;
  }
}

/**
 * Whether the content violates [OpenAI's usage policies](/policies/usage-policies).
 * @member {Boolean} flagged
 */
CreateModerationResponseResults.prototype.flagged = undefined;

/**
 * @member {module:model/CreateModerationResponseCategories} categories
 */
CreateModerationResponseResults.prototype.categories = undefined;

/**
 * @member {module:model/CreateModerationResponseCategoryScores} categoryScores
 */
CreateModerationResponseResults.prototype.categoryScores = undefined;

