/*
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.50
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {CreateFineTuneRequestHyperparameters} from './CreateFineTuneRequestHyperparameters';

/**
 * The CreateFineTuneRequest model module.
 * @module model/CreateFineTuneRequest
 * @version 2.0.0
 */
export class CreateFineTuneRequest {
  /**
   * Constructs a new <code>CreateFineTuneRequest</code>.
   * @alias module:model/CreateFineTuneRequest
   * @class
   * @param trainingFile {String} The ID of an uploaded file that contains training data.  See [upload file](/docs/api-reference/files/upload) for how to upload a file.  Your dataset must be formatted as a JSONL file, where each training example is a JSON object with the keys \"prompt\" and \"completion\". Additionally, you must upload your file with the purpose `fine-tune`.  See the [fine-tuning guide](/docs/guides/legacy-fine-tuning/creating-training-data) for more details. 
   */
  constructor(trainingFile) {
    this.trainingFile = trainingFile;
  }

  /**
   * Constructs a <code>CreateFineTuneRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CreateFineTuneRequest} obj Optional instance to populate.
   * @return {module:model/CreateFineTuneRequest} The populated <code>CreateFineTuneRequest</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CreateFineTuneRequest();
      if (data.hasOwnProperty('training_file'))
        obj.trainingFile = ApiClient.convertToType(data['training_file'], 'String');
      if (data.hasOwnProperty('batch_size'))
        obj.batchSize = ApiClient.convertToType(data['batch_size'], 'Number');
      if (data.hasOwnProperty('classification_betas'))
        obj.classificationBetas = ApiClient.convertToType(data['classification_betas'], ['Number']);
      if (data.hasOwnProperty('classification_n_classes'))
        obj.classificationNClasses = ApiClient.convertToType(data['classification_n_classes'], 'Number');
      if (data.hasOwnProperty('classification_positive_class'))
        obj.classificationPositiveClass = ApiClient.convertToType(data['classification_positive_class'], 'String');
      if (data.hasOwnProperty('compute_classification_metrics'))
        obj.computeClassificationMetrics = ApiClient.convertToType(data['compute_classification_metrics'], 'Boolean');
      if (data.hasOwnProperty('hyperparameters'))
        obj.hyperparameters = CreateFineTuneRequestHyperparameters.constructFromObject(data['hyperparameters']);
      if (data.hasOwnProperty('learning_rate_multiplier'))
        obj.learningRateMultiplier = ApiClient.convertToType(data['learning_rate_multiplier'], 'Number');
      if (data.hasOwnProperty('model'))
        obj.model = ApiClient.convertToType(data['model'], Object);
      if (data.hasOwnProperty('prompt_loss_weight'))
        obj.promptLossWeight = ApiClient.convertToType(data['prompt_loss_weight'], 'Number');
      if (data.hasOwnProperty('suffix'))
        obj.suffix = ApiClient.convertToType(data['suffix'], 'String');
      if (data.hasOwnProperty('validation_file'))
        obj.validationFile = ApiClient.convertToType(data['validation_file'], 'String');
    }
    return obj;
  }
}

/**
 * The ID of an uploaded file that contains training data.  See [upload file](/docs/api-reference/files/upload) for how to upload a file.  Your dataset must be formatted as a JSONL file, where each training example is a JSON object with the keys \"prompt\" and \"completion\". Additionally, you must upload your file with the purpose `fine-tune`.  See the [fine-tuning guide](/docs/guides/legacy-fine-tuning/creating-training-data) for more details. 
 * @member {String} trainingFile
 */
CreateFineTuneRequest.prototype.trainingFile = undefined;

/**
 * The batch size to use for training. The batch size is the number of training examples used to train a single forward and backward pass.  By default, the batch size will be dynamically configured to be ~0.2% of the number of examples in the training set, capped at 256 - in general, we've found that larger batch sizes tend to work better for larger datasets. 
 * @member {Number} batchSize
 */
CreateFineTuneRequest.prototype.batchSize = undefined;

/**
 * If this is provided, we calculate F-beta scores at the specified beta values. The F-beta score is a generalization of F-1 score. This is only used for binary classification.  With a beta of 1 (i.e. the F-1 score), precision and recall are given the same weight. A larger beta score puts more weight on recall and less on precision. A smaller beta score puts more weight on precision and less on recall. 
 * @member {Array.<Number>} classificationBetas
 */
CreateFineTuneRequest.prototype.classificationBetas = undefined;

/**
 * The number of classes in a classification task.  This parameter is required for multiclass classification. 
 * @member {Number} classificationNClasses
 */
CreateFineTuneRequest.prototype.classificationNClasses = undefined;

/**
 * The positive class in binary classification.  This parameter is needed to generate precision, recall, and F1 metrics when doing binary classification. 
 * @member {String} classificationPositiveClass
 */
CreateFineTuneRequest.prototype.classificationPositiveClass = undefined;

/**
 * If set, we calculate classification-specific metrics such as accuracy and F-1 score using the validation set at the end of every epoch. These metrics can be viewed in the [results file](/docs/guides/legacy-fine-tuning/analyzing-your-fine-tuned-model).  In order to compute classification metrics, you must provide a `validation_file`. Additionally, you must specify `classification_n_classes` for multiclass classification or `classification_positive_class` for binary classification. 
 * @member {Boolean} computeClassificationMetrics
 * @default false
 */
CreateFineTuneRequest.prototype.computeClassificationMetrics = false;

/**
 * @member {module:model/CreateFineTuneRequestHyperparameters} hyperparameters
 */
CreateFineTuneRequest.prototype.hyperparameters = undefined;

/**
 * The learning rate multiplier to use for training. The fine-tuning learning rate is the original learning rate used for pretraining multiplied by this value.  By default, the learning rate multiplier is the 0.05, 0.1, or 0.2 depending on final `batch_size` (larger learning rates tend to perform better with larger batch sizes). We recommend experimenting with values in the range 0.02 to 0.2 to see what produces the best results. 
 * @member {Number} learningRateMultiplier
 */
CreateFineTuneRequest.prototype.learningRateMultiplier = undefined;

/**
 * The name of the base model to fine-tune. You can select one of \"ada\", \"babbage\", \"curie\", \"davinci\", or a fine-tuned model created after 2022-04-21 and before 2023-08-22. To learn more about these models, see the [Models](/docs/models) documentation. 
 * @member {Object} model
 */
CreateFineTuneRequest.prototype.model = undefined;

/**
 * The weight to use for loss on the prompt tokens. This controls how much the model tries to learn to generate the prompt (as compared to the completion which always has a weight of 1.0), and can add a stabilizing effect to training when completions are short.  If prompts are extremely long (relative to completions), it may make sense to reduce this weight so as to avoid over-prioritizing learning the prompt. 
 * @member {Number} promptLossWeight
 * @default 0.01
 */
CreateFineTuneRequest.prototype.promptLossWeight = 0.01;

/**
 * A string of up to 40 characters that will be added to your fine-tuned model name.  For example, a `suffix` of \"custom-model-name\" would produce a model name like `ada:ft-your-org:custom-model-name-2022-02-15-04-21-04`. 
 * @member {String} suffix
 */
CreateFineTuneRequest.prototype.suffix = undefined;

/**
 * The ID of an uploaded file that contains validation data.  If you provide this file, the data is used to generate validation metrics periodically during fine-tuning. These metrics can be viewed in the [fine-tuning results file](/docs/guides/legacy-fine-tuning/analyzing-your-fine-tuned-model). Your train and validation data should be mutually exclusive.  Your dataset must be formatted as a JSONL file, where each validation example is a JSON object with the keys \"prompt\" and \"completion\". Additionally, you must upload your file with the purpose `fine-tune`.  See the [fine-tuning guide](/docs/guides/legacy-fine-tuning/creating-training-data) for more details. 
 * @member {String} validationFile
 */
CreateFineTuneRequest.prototype.validationFile = undefined;

