/*
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.50
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {CompletionUsage} from './CompletionUsage';
import {CreateEditResponseChoices} from './CreateEditResponseChoices';

/**
 * The CreateEditResponse model module.
 * @module model/CreateEditResponse
 * @version 2.0.0
 */
export class CreateEditResponse {
  /**
   * Constructs a new <code>CreateEditResponse</code>.
   * @alias module:model/CreateEditResponse
   * @class
   * @param choices {Array.<module:model/CreateEditResponseChoices>} A list of edit choices. Can be more than one if `n` is greater than 1.
   * @param _object {module:model/CreateEditResponse.ObjectEnum} The object type, which is always `edit`.
   * @param created {Number} The Unix timestamp (in seconds) of when the edit was created.
   * @param usage {module:model/CompletionUsage} 
   */
  constructor(choices, _object, created, usage) {
    this.choices = choices;
    this._object = _object;
    this.created = created;
    this.usage = usage;
  }

  /**
   * Constructs a <code>CreateEditResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CreateEditResponse} obj Optional instance to populate.
   * @return {module:model/CreateEditResponse} The populated <code>CreateEditResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CreateEditResponse();
      if (data.hasOwnProperty('choices'))
        obj.choices = ApiClient.convertToType(data['choices'], [CreateEditResponseChoices]);
      if (data.hasOwnProperty('object'))
        obj._object = ApiClient.convertToType(data['object'], 'String');
      if (data.hasOwnProperty('created'))
        obj.created = ApiClient.convertToType(data['created'], 'Number');
      if (data.hasOwnProperty('usage'))
        obj.usage = CompletionUsage.constructFromObject(data['usage']);
    }
    return obj;
  }
}

/**
 * A list of edit choices. Can be more than one if `n` is greater than 1.
 * @member {Array.<module:model/CreateEditResponseChoices>} choices
 */
CreateEditResponse.prototype.choices = undefined;

/**
 * Allowed values for the <code>_object</code> property.
 * @enum {String}
 * @readonly
 */
CreateEditResponse.ObjectEnum = {
  /**
   * value: "edit"
   * @const
   */
  edit: "edit"
};
/**
 * The object type, which is always `edit`.
 * @member {module:model/CreateEditResponse.ObjectEnum} _object
 */
CreateEditResponse.prototype._object = undefined;

/**
 * The Unix timestamp (in seconds) of when the edit was created.
 * @member {Number} created
 */
CreateEditResponse.prototype.created = undefined;

/**
 * @member {module:model/CompletionUsage} usage
 */
CreateEditResponse.prototype.usage = undefined;

