/*
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.50
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The CreateImageEditRequest model module.
 * @module model/CreateImageEditRequest
 * @version 2.0.0
 */
export class CreateImageEditRequest {
  /**
   * Constructs a new <code>CreateImageEditRequest</code>.
   * @alias module:model/CreateImageEditRequest
   * @class
   * @param image {Blob} The image to edit. Must be a valid PNG file, less than 4MB, and square. If mask is not provided, image must have transparency, which will be used as the mask.
   * @param prompt {String} A text description of the desired image(s). The maximum length is 1000 characters.
   */
  constructor(image, prompt) {
    this.image = image;
    this.prompt = prompt;
  }

  /**
   * Constructs a <code>CreateImageEditRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CreateImageEditRequest} obj Optional instance to populate.
   * @return {module:model/CreateImageEditRequest} The populated <code>CreateImageEditRequest</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CreateImageEditRequest();
      if (data.hasOwnProperty('image'))
        obj.image = ApiClient.convertToType(data['image'], 'Blob');
      if (data.hasOwnProperty('prompt'))
        obj.prompt = ApiClient.convertToType(data['prompt'], 'String');
      if (data.hasOwnProperty('mask'))
        obj.mask = ApiClient.convertToType(data['mask'], 'Blob');
      if (data.hasOwnProperty('model'))
        obj.model = ApiClient.convertToType(data['model'], Object);
      if (data.hasOwnProperty('n'))
        obj.n = ApiClient.convertToType(data['n'], 'Number');
      if (data.hasOwnProperty('size'))
        obj.size = ApiClient.convertToType(data['size'], 'String');
      if (data.hasOwnProperty('response_format'))
        obj.responseFormat = ApiClient.convertToType(data['response_format'], 'String');
      if (data.hasOwnProperty('user'))
        obj.user = ApiClient.convertToType(data['user'], 'String');
    }
    return obj;
  }
}

/**
 * The image to edit. Must be a valid PNG file, less than 4MB, and square. If mask is not provided, image must have transparency, which will be used as the mask.
 * @member {Blob} image
 */
CreateImageEditRequest.prototype.image = undefined;

/**
 * A text description of the desired image(s). The maximum length is 1000 characters.
 * @member {String} prompt
 */
CreateImageEditRequest.prototype.prompt = undefined;

/**
 * An additional image whose fully transparent areas (e.g. where alpha is zero) indicate where `image` should be edited. Must be a valid PNG file, less than 4MB, and have the same dimensions as `image`.
 * @member {Blob} mask
 */
CreateImageEditRequest.prototype.mask = undefined;

/**
 * The model to use for image generation. Only `dall-e-2` is supported at this time.
 * @member {Object} model
 */
CreateImageEditRequest.prototype.model = undefined;

/**
 * The number of images to generate. Must be between 1 and 10.
 * @member {Number} n
 * @default 1
 */
CreateImageEditRequest.prototype.n = 1;

/**
 * Allowed values for the <code>size</code> property.
 * @enum {String}
 * @readonly
 */
CreateImageEditRequest.SizeEnum = {
  /**
   * value: "256x256"
   * @const
   */
  _256x256: "256x256",

  /**
   * value: "512x512"
   * @const
   */
  _512x512: "512x512",

  /**
   * value: "1024x1024"
   * @const
   */
  _1024x1024: "1024x1024"
};
/**
 * The size of the generated images. Must be one of `256x256`, `512x512`, or `1024x1024`.
 * @member {module:model/CreateImageEditRequest.SizeEnum} size
 * @default '1024x1024'
 */
CreateImageEditRequest.prototype.size = '1024x1024';

/**
 * Allowed values for the <code>responseFormat</code> property.
 * @enum {String}
 * @readonly
 */
CreateImageEditRequest.ResponseFormatEnum = {
  /**
   * value: "url"
   * @const
   */
  url: "url",

  /**
   * value: "b64_json"
   * @const
   */
  b64Json: "b64_json"
};
/**
 * The format in which the generated images are returned. Must be one of `url` or `b64_json`.
 * @member {module:model/CreateImageEditRequest.ResponseFormatEnum} responseFormat
 * @default 'url'
 */
CreateImageEditRequest.prototype.responseFormat = 'url';

/**
 * A unique identifier representing your end-user, which can help OpenAI to monitor and detect abuse. [Learn more](/docs/guides/safety-best-practices/end-user-ids). 
 * @member {String} user
 */
CreateImageEditRequest.prototype.user = undefined;

