/*
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.50
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {CreateChatCompletionStreamResponseChoices} from './CreateChatCompletionStreamResponseChoices';

/**
 * The CreateChatCompletionStreamResponse model module.
 * @module model/CreateChatCompletionStreamResponse
 * @version 2.0.0
 */
export class CreateChatCompletionStreamResponse {
  /**
   * Constructs a new <code>CreateChatCompletionStreamResponse</code>.
   * Represents a streamed chunk of a chat completion response returned by model, based on the provided input.
   * @alias module:model/CreateChatCompletionStreamResponse
   * @class
   * @param id {String} A unique identifier for the chat completion. Each chunk has the same ID.
   * @param choices {Array.<module:model/CreateChatCompletionStreamResponseChoices>} A list of chat completion choices. Can be more than one if `n` is greater than 1.
   * @param created {Number} The Unix timestamp (in seconds) of when the chat completion was created. Each chunk has the same timestamp.
   * @param model {String} The model to generate the completion.
   * @param _object {module:model/CreateChatCompletionStreamResponse.ObjectEnum} The object type, which is always `chat.completion.chunk`.
   */
  constructor(id, choices, created, model, _object) {
    this.id = id;
    this.choices = choices;
    this.created = created;
    this.model = model;
    this._object = _object;
  }

  /**
   * Constructs a <code>CreateChatCompletionStreamResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CreateChatCompletionStreamResponse} obj Optional instance to populate.
   * @return {module:model/CreateChatCompletionStreamResponse} The populated <code>CreateChatCompletionStreamResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CreateChatCompletionStreamResponse();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('choices'))
        obj.choices = ApiClient.convertToType(data['choices'], [CreateChatCompletionStreamResponseChoices]);
      if (data.hasOwnProperty('created'))
        obj.created = ApiClient.convertToType(data['created'], 'Number');
      if (data.hasOwnProperty('model'))
        obj.model = ApiClient.convertToType(data['model'], 'String');
      if (data.hasOwnProperty('object'))
        obj._object = ApiClient.convertToType(data['object'], 'String');
    }
    return obj;
  }
}

/**
 * A unique identifier for the chat completion. Each chunk has the same ID.
 * @member {String} id
 */
CreateChatCompletionStreamResponse.prototype.id = undefined;

/**
 * A list of chat completion choices. Can be more than one if `n` is greater than 1.
 * @member {Array.<module:model/CreateChatCompletionStreamResponseChoices>} choices
 */
CreateChatCompletionStreamResponse.prototype.choices = undefined;

/**
 * The Unix timestamp (in seconds) of when the chat completion was created. Each chunk has the same timestamp.
 * @member {Number} created
 */
CreateChatCompletionStreamResponse.prototype.created = undefined;

/**
 * The model to generate the completion.
 * @member {String} model
 */
CreateChatCompletionStreamResponse.prototype.model = undefined;

/**
 * Allowed values for the <code>_object</code> property.
 * @enum {String}
 * @readonly
 */
CreateChatCompletionStreamResponse.ObjectEnum = {
  /**
   * value: "chat.completion.chunk"
   * @const
   */
  chatCompletionChunk: "chat.completion.chunk"
};
/**
 * The object type, which is always `chat.completion.chunk`.
 * @member {module:model/CreateChatCompletionStreamResponse.ObjectEnum} _object
 */
CreateChatCompletionStreamResponse.prototype._object = undefined;

