/*
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.50
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {CreateCompletionResponseLogprobs} from './CreateCompletionResponseLogprobs';

/**
 * The CreateCompletionResponseChoices model module.
 * @module model/CreateCompletionResponseChoices
 * @version 2.0.0
 */
export class CreateCompletionResponseChoices {
  /**
   * Constructs a new <code>CreateCompletionResponseChoices</code>.
   * @alias module:model/CreateCompletionResponseChoices
   * @class
   * @param finishReason {module:model/CreateCompletionResponseChoices.FinishReasonEnum} The reason the model stopped generating tokens. This will be `stop` if the model hit a natural stop point or a provided stop sequence, `length` if the maximum number of tokens specified in the request was reached, or `content_filter` if content was omitted due to a flag from our content filters. 
   * @param index {Number} 
   * @param logprobs {module:model/CreateCompletionResponseLogprobs} 
   * @param text {String} 
   */
  constructor(finishReason, index, logprobs, text) {
    this.finishReason = finishReason;
    this.index = index;
    this.logprobs = logprobs;
    this.text = text;
  }

  /**
   * Constructs a <code>CreateCompletionResponseChoices</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CreateCompletionResponseChoices} obj Optional instance to populate.
   * @return {module:model/CreateCompletionResponseChoices} The populated <code>CreateCompletionResponseChoices</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CreateCompletionResponseChoices();
      if (data.hasOwnProperty('finish_reason'))
        obj.finishReason = ApiClient.convertToType(data['finish_reason'], 'String');
      if (data.hasOwnProperty('index'))
        obj.index = ApiClient.convertToType(data['index'], 'Number');
      if (data.hasOwnProperty('logprobs'))
        obj.logprobs = CreateCompletionResponseLogprobs.constructFromObject(data['logprobs']);
      if (data.hasOwnProperty('text'))
        obj.text = ApiClient.convertToType(data['text'], 'String');
    }
    return obj;
  }
}

/**
 * Allowed values for the <code>finishReason</code> property.
 * @enum {String}
 * @readonly
 */
CreateCompletionResponseChoices.FinishReasonEnum = {
  /**
   * value: "stop"
   * @const
   */
  stop: "stop",

  /**
   * value: "length"
   * @const
   */
  length: "length",

  /**
   * value: "content_filter"
   * @const
   */
  contentFilter: "content_filter"
};
/**
 * The reason the model stopped generating tokens. This will be `stop` if the model hit a natural stop point or a provided stop sequence, `length` if the maximum number of tokens specified in the request was reached, or `content_filter` if content was omitted due to a flag from our content filters. 
 * @member {module:model/CreateCompletionResponseChoices.FinishReasonEnum} finishReason
 */
CreateCompletionResponseChoices.prototype.finishReason = undefined;

/**
 * @member {Number} index
 */
CreateCompletionResponseChoices.prototype.index = undefined;

/**
 * @member {module:model/CreateCompletionResponseLogprobs} logprobs
 */
CreateCompletionResponseChoices.prototype.logprobs = undefined;

/**
 * @member {String} text
 */
CreateCompletionResponseChoices.prototype.text = undefined;

