/*
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.50
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The DeleteAssistantResponse model module.
 * @module model/DeleteAssistantResponse
 * @version 2.0.0
 */
export class DeleteAssistantResponse {
  /**
   * Constructs a new <code>DeleteAssistantResponse</code>.
   * @alias module:model/DeleteAssistantResponse
   * @class
   * @param id {String} 
   * @param deleted {Boolean} 
   * @param _object {module:model/DeleteAssistantResponse.ObjectEnum} 
   */
  constructor(id, deleted, _object) {
    this.id = id;
    this.deleted = deleted;
    this._object = _object;
  }

  /**
   * Constructs a <code>DeleteAssistantResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DeleteAssistantResponse} obj Optional instance to populate.
   * @return {module:model/DeleteAssistantResponse} The populated <code>DeleteAssistantResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new DeleteAssistantResponse();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('deleted'))
        obj.deleted = ApiClient.convertToType(data['deleted'], 'Boolean');
      if (data.hasOwnProperty('object'))
        obj._object = ApiClient.convertToType(data['object'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
DeleteAssistantResponse.prototype.id = undefined;

/**
 * @member {Boolean} deleted
 */
DeleteAssistantResponse.prototype.deleted = undefined;

/**
 * Allowed values for the <code>_object</code> property.
 * @enum {String}
 * @readonly
 */
DeleteAssistantResponse.ObjectEnum = {
  /**
   * value: "assistant.deleted"
   * @const
   */
  assistantDeleted: "assistant.deleted"
};
/**
 * @member {module:model/DeleteAssistantResponse.ObjectEnum} _object
 */
DeleteAssistantResponse.prototype._object = undefined;

