/*
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.50
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The DeleteFileResponse model module.
 * @module model/DeleteFileResponse
 * @version 2.0.0
 */
export class DeleteFileResponse {
  /**
   * Constructs a new <code>DeleteFileResponse</code>.
   * @alias module:model/DeleteFileResponse
   * @class
   * @param id {String} 
   * @param _object {module:model/DeleteFileResponse.ObjectEnum} 
   * @param deleted {Boolean} 
   */
  constructor(id, _object, deleted) {
    this.id = id;
    this._object = _object;
    this.deleted = deleted;
  }

  /**
   * Constructs a <code>DeleteFileResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DeleteFileResponse} obj Optional instance to populate.
   * @return {module:model/DeleteFileResponse} The populated <code>DeleteFileResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new DeleteFileResponse();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('object'))
        obj._object = ApiClient.convertToType(data['object'], 'String');
      if (data.hasOwnProperty('deleted'))
        obj.deleted = ApiClient.convertToType(data['deleted'], 'Boolean');
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
DeleteFileResponse.prototype.id = undefined;

/**
 * Allowed values for the <code>_object</code> property.
 * @enum {String}
 * @readonly
 */
DeleteFileResponse.ObjectEnum = {
  /**
   * value: "file"
   * @const
   */
  file: "file"
};
/**
 * @member {module:model/DeleteFileResponse.ObjectEnum} _object
 */
DeleteFileResponse.prototype._object = undefined;

/**
 * @member {Boolean} deleted
 */
DeleteFileResponse.prototype.deleted = undefined;

