/*
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.50
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {FineTuningJobError} from './FineTuningJobError';
import {FineTuningJobHyperparameters} from './FineTuningJobHyperparameters';

/**
 * The FineTuningJob model module.
 * @module model/FineTuningJob
 * @version 2.0.0
 */
export class FineTuningJob {
  /**
   * Constructs a new <code>FineTuningJob</code>.
   * The &#x60;fine_tuning.job&#x60; object represents a fine-tuning job that has been created through the API. 
   * @alias module:model/FineTuningJob
   * @class
   * @param id {String} The object identifier, which can be referenced in the API endpoints.
   * @param createdAt {Number} The Unix timestamp (in seconds) for when the fine-tuning job was created.
   * @param error {module:model/FineTuningJobError} 
   * @param fineTunedModel {String} The name of the fine-tuned model that is being created. The value will be null if the fine-tuning job is still running.
   * @param finishedAt {Number} The Unix timestamp (in seconds) for when the fine-tuning job was finished. The value will be null if the fine-tuning job is still running.
   * @param hyperparameters {module:model/FineTuningJobHyperparameters} 
   * @param model {String} The base model that is being fine-tuned.
   * @param _object {module:model/FineTuningJob.ObjectEnum} The object type, which is always \"fine_tuning.job\".
   * @param organizationId {String} The organization that owns the fine-tuning job.
   * @param resultFiles {Array.<String>} The compiled results file ID(s) for the fine-tuning job. You can retrieve the results with the [Files API](/docs/api-reference/files/retrieve-contents).
   * @param status {module:model/FineTuningJob.StatusEnum} The current status of the fine-tuning job, which can be either `validating_files`, `queued`, `running`, `succeeded`, `failed`, or `cancelled`.
   * @param trainedTokens {Number} The total number of billable tokens processed by this fine-tuning job. The value will be null if the fine-tuning job is still running.
   * @param trainingFile {String} The file ID used for training. You can retrieve the training data with the [Files API](/docs/api-reference/files/retrieve-contents).
   * @param validationFile {String} The file ID used for validation. You can retrieve the validation results with the [Files API](/docs/api-reference/files/retrieve-contents).
   */
  constructor(id, createdAt, error, fineTunedModel, finishedAt, hyperparameters, model, _object, organizationId, resultFiles, status, trainedTokens, trainingFile, validationFile) {
    this.id = id;
    this.createdAt = createdAt;
    this.error = error;
    this.fineTunedModel = fineTunedModel;
    this.finishedAt = finishedAt;
    this.hyperparameters = hyperparameters;
    this.model = model;
    this._object = _object;
    this.organizationId = organizationId;
    this.resultFiles = resultFiles;
    this.status = status;
    this.trainedTokens = trainedTokens;
    this.trainingFile = trainingFile;
    this.validationFile = validationFile;
  }

  /**
   * Constructs a <code>FineTuningJob</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/FineTuningJob} obj Optional instance to populate.
   * @return {module:model/FineTuningJob} The populated <code>FineTuningJob</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new FineTuningJob();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('created_at'))
        obj.createdAt = ApiClient.convertToType(data['created_at'], 'Number');
      if (data.hasOwnProperty('error'))
        obj.error = FineTuningJobError.constructFromObject(data['error']);
      if (data.hasOwnProperty('fine_tuned_model'))
        obj.fineTunedModel = ApiClient.convertToType(data['fine_tuned_model'], 'String');
      if (data.hasOwnProperty('finished_at'))
        obj.finishedAt = ApiClient.convertToType(data['finished_at'], 'Number');
      if (data.hasOwnProperty('hyperparameters'))
        obj.hyperparameters = FineTuningJobHyperparameters.constructFromObject(data['hyperparameters']);
      if (data.hasOwnProperty('model'))
        obj.model = ApiClient.convertToType(data['model'], 'String');
      if (data.hasOwnProperty('object'))
        obj._object = ApiClient.convertToType(data['object'], 'String');
      if (data.hasOwnProperty('organization_id'))
        obj.organizationId = ApiClient.convertToType(data['organization_id'], 'String');
      if (data.hasOwnProperty('result_files'))
        obj.resultFiles = ApiClient.convertToType(data['result_files'], ['String']);
      if (data.hasOwnProperty('status'))
        obj.status = ApiClient.convertToType(data['status'], 'String');
      if (data.hasOwnProperty('trained_tokens'))
        obj.trainedTokens = ApiClient.convertToType(data['trained_tokens'], 'Number');
      if (data.hasOwnProperty('training_file'))
        obj.trainingFile = ApiClient.convertToType(data['training_file'], 'String');
      if (data.hasOwnProperty('validation_file'))
        obj.validationFile = ApiClient.convertToType(data['validation_file'], 'String');
    }
    return obj;
  }
}

/**
 * The object identifier, which can be referenced in the API endpoints.
 * @member {String} id
 */
FineTuningJob.prototype.id = undefined;

/**
 * The Unix timestamp (in seconds) for when the fine-tuning job was created.
 * @member {Number} createdAt
 */
FineTuningJob.prototype.createdAt = undefined;

/**
 * @member {module:model/FineTuningJobError} error
 */
FineTuningJob.prototype.error = undefined;

/**
 * The name of the fine-tuned model that is being created. The value will be null if the fine-tuning job is still running.
 * @member {String} fineTunedModel
 */
FineTuningJob.prototype.fineTunedModel = undefined;

/**
 * The Unix timestamp (in seconds) for when the fine-tuning job was finished. The value will be null if the fine-tuning job is still running.
 * @member {Number} finishedAt
 */
FineTuningJob.prototype.finishedAt = undefined;

/**
 * @member {module:model/FineTuningJobHyperparameters} hyperparameters
 */
FineTuningJob.prototype.hyperparameters = undefined;

/**
 * The base model that is being fine-tuned.
 * @member {String} model
 */
FineTuningJob.prototype.model = undefined;

/**
 * Allowed values for the <code>_object</code> property.
 * @enum {String}
 * @readonly
 */
FineTuningJob.ObjectEnum = {
  /**
   * value: "fine_tuning.job"
   * @const
   */
  fineTuningJob: "fine_tuning.job"
};
/**
 * The object type, which is always \"fine_tuning.job\".
 * @member {module:model/FineTuningJob.ObjectEnum} _object
 */
FineTuningJob.prototype._object = undefined;

/**
 * The organization that owns the fine-tuning job.
 * @member {String} organizationId
 */
FineTuningJob.prototype.organizationId = undefined;

/**
 * The compiled results file ID(s) for the fine-tuning job. You can retrieve the results with the [Files API](/docs/api-reference/files/retrieve-contents).
 * @member {Array.<String>} resultFiles
 */
FineTuningJob.prototype.resultFiles = undefined;

/**
 * Allowed values for the <code>status</code> property.
 * @enum {String}
 * @readonly
 */
FineTuningJob.StatusEnum = {
  /**
   * value: "validating_files"
   * @const
   */
  validatingFiles: "validating_files",

  /**
   * value: "queued"
   * @const
   */
  queued: "queued",

  /**
   * value: "running"
   * @const
   */
  running: "running",

  /**
   * value: "succeeded"
   * @const
   */
  succeeded: "succeeded",

  /**
   * value: "failed"
   * @const
   */
  failed: "failed",

  /**
   * value: "cancelled"
   * @const
   */
  cancelled: "cancelled"
};
/**
 * The current status of the fine-tuning job, which can be either `validating_files`, `queued`, `running`, `succeeded`, `failed`, or `cancelled`.
 * @member {module:model/FineTuningJob.StatusEnum} status
 */
FineTuningJob.prototype.status = undefined;

/**
 * The total number of billable tokens processed by this fine-tuning job. The value will be null if the fine-tuning job is still running.
 * @member {Number} trainedTokens
 */
FineTuningJob.prototype.trainedTokens = undefined;

/**
 * The file ID used for training. You can retrieve the training data with the [Files API](/docs/api-reference/files/retrieve-contents).
 * @member {String} trainingFile
 */
FineTuningJob.prototype.trainingFile = undefined;

/**
 * The file ID used for validation. You can retrieve the validation results with the [Files API](/docs/api-reference/files/retrieve-contents).
 * @member {String} validationFile
 */
FineTuningJob.prototype.validationFile = undefined;

