/*
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.50
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The FineTuningJobEvent model module.
 * @module model/FineTuningJobEvent
 * @version 2.0.0
 */
export class FineTuningJobEvent {
  /**
   * Constructs a new <code>FineTuningJobEvent</code>.
   * Fine-tuning job event object
   * @alias module:model/FineTuningJobEvent
   * @class
   * @param id {String} 
   * @param createdAt {Number} 
   * @param level {module:model/FineTuningJobEvent.LevelEnum} 
   * @param message {String} 
   * @param _object {module:model/FineTuningJobEvent.ObjectEnum} 
   */
  constructor(id, createdAt, level, message, _object) {
    this.id = id;
    this.createdAt = createdAt;
    this.level = level;
    this.message = message;
    this._object = _object;
  }

  /**
   * Constructs a <code>FineTuningJobEvent</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/FineTuningJobEvent} obj Optional instance to populate.
   * @return {module:model/FineTuningJobEvent} The populated <code>FineTuningJobEvent</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new FineTuningJobEvent();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('created_at'))
        obj.createdAt = ApiClient.convertToType(data['created_at'], 'Number');
      if (data.hasOwnProperty('level'))
        obj.level = ApiClient.convertToType(data['level'], 'String');
      if (data.hasOwnProperty('message'))
        obj.message = ApiClient.convertToType(data['message'], 'String');
      if (data.hasOwnProperty('object'))
        obj._object = ApiClient.convertToType(data['object'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
FineTuningJobEvent.prototype.id = undefined;

/**
 * @member {Number} createdAt
 */
FineTuningJobEvent.prototype.createdAt = undefined;

/**
 * Allowed values for the <code>level</code> property.
 * @enum {String}
 * @readonly
 */
FineTuningJobEvent.LevelEnum = {
  /**
   * value: "info"
   * @const
   */
  info: "info",

  /**
   * value: "warn"
   * @const
   */
  warn: "warn",

  /**
   * value: "error"
   * @const
   */
  error: "error"
};
/**
 * @member {module:model/FineTuningJobEvent.LevelEnum} level
 */
FineTuningJobEvent.prototype.level = undefined;

/**
 * @member {String} message
 */
FineTuningJobEvent.prototype.message = undefined;

/**
 * Allowed values for the <code>_object</code> property.
 * @enum {String}
 * @readonly
 */
FineTuningJobEvent.ObjectEnum = {
  /**
   * value: "fine_tuning.job.event"
   * @const
   */
  fineTuningJobEvent: "fine_tuning.job.event"
};
/**
 * @member {module:model/FineTuningJobEvent.ObjectEnum} _object
 */
FineTuningJobEvent.prototype._object = undefined;

