/*
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.50
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {FineTuningJob} from './FineTuningJob';

/**
 * The ListPaginatedFineTuningJobsResponse model module.
 * @module model/ListPaginatedFineTuningJobsResponse
 * @version 2.0.0
 */
export class ListPaginatedFineTuningJobsResponse {
  /**
   * Constructs a new <code>ListPaginatedFineTuningJobsResponse</code>.
   * @alias module:model/ListPaginatedFineTuningJobsResponse
   * @class
   * @param data {Array.<module:model/FineTuningJob>} 
   * @param hasMore {Boolean} 
   * @param _object {module:model/ListPaginatedFineTuningJobsResponse.ObjectEnum} 
   */
  constructor(data, hasMore, _object) {
    this.data = data;
    this.hasMore = hasMore;
    this._object = _object;
  }

  /**
   * Constructs a <code>ListPaginatedFineTuningJobsResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ListPaginatedFineTuningJobsResponse} obj Optional instance to populate.
   * @return {module:model/ListPaginatedFineTuningJobsResponse} The populated <code>ListPaginatedFineTuningJobsResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ListPaginatedFineTuningJobsResponse();
      if (data.hasOwnProperty('data'))
        obj.data = ApiClient.convertToType(data['data'], [FineTuningJob]);
      if (data.hasOwnProperty('has_more'))
        obj.hasMore = ApiClient.convertToType(data['has_more'], 'Boolean');
      if (data.hasOwnProperty('object'))
        obj._object = ApiClient.convertToType(data['object'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Array.<module:model/FineTuningJob>} data
 */
ListPaginatedFineTuningJobsResponse.prototype.data = undefined;

/**
 * @member {Boolean} hasMore
 */
ListPaginatedFineTuningJobsResponse.prototype.hasMore = undefined;

/**
 * Allowed values for the <code>_object</code> property.
 * @enum {String}
 * @readonly
 */
ListPaginatedFineTuningJobsResponse.ObjectEnum = {
  /**
   * value: "list"
   * @const
   */
  list: "list"
};
/**
 * @member {module:model/ListPaginatedFineTuningJobsResponse.ObjectEnum} _object
 */
ListPaginatedFineTuningJobsResponse.prototype._object = undefined;

