/*
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.50
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {MessageObject} from './MessageObject';

/**
 * The ListMessagesResponse model module.
 * @module model/ListMessagesResponse
 * @version 2.0.0
 */
export class ListMessagesResponse {
  /**
   * Constructs a new <code>ListMessagesResponse</code>.
   * @alias module:model/ListMessagesResponse
   * @class
   * @param _object {String} 
   * @param data {Array.<module:model/MessageObject>} 
   * @param firstId {String} 
   * @param lastId {String} 
   * @param hasMore {Boolean} 
   */
  constructor(_object, data, firstId, lastId, hasMore) {
    this._object = _object;
    this.data = data;
    this.firstId = firstId;
    this.lastId = lastId;
    this.hasMore = hasMore;
  }

  /**
   * Constructs a <code>ListMessagesResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ListMessagesResponse} obj Optional instance to populate.
   * @return {module:model/ListMessagesResponse} The populated <code>ListMessagesResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ListMessagesResponse();
      if (data.hasOwnProperty('object'))
        obj._object = ApiClient.convertToType(data['object'], 'String');
      if (data.hasOwnProperty('data'))
        obj.data = ApiClient.convertToType(data['data'], [MessageObject]);
      if (data.hasOwnProperty('first_id'))
        obj.firstId = ApiClient.convertToType(data['first_id'], 'String');
      if (data.hasOwnProperty('last_id'))
        obj.lastId = ApiClient.convertToType(data['last_id'], 'String');
      if (data.hasOwnProperty('has_more'))
        obj.hasMore = ApiClient.convertToType(data['has_more'], 'Boolean');
    }
    return obj;
  }
}

/**
 * @member {String} _object
 */
ListMessagesResponse.prototype._object = undefined;

/**
 * @member {Array.<module:model/MessageObject>} data
 */
ListMessagesResponse.prototype.data = undefined;

/**
 * @member {String} firstId
 */
ListMessagesResponse.prototype.firstId = undefined;

/**
 * @member {String} lastId
 */
ListMessagesResponse.prototype.lastId = undefined;

/**
 * @member {Boolean} hasMore
 */
ListMessagesResponse.prototype.hasMore = undefined;

