/*
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.50
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {MessageContentImageFileObjectImageFile} from './MessageContentImageFileObjectImageFile';

/**
 * The MessageContentImageFileObject model module.
 * @module model/MessageContentImageFileObject
 * @version 2.0.0
 */
export class MessageContentImageFileObject {
  /**
   * Constructs a new <code>MessageContentImageFileObject</code>.
   * References an image [File](/docs/api-reference/files) in the content of a message.
   * @alias module:model/MessageContentImageFileObject
   * @class
   * @param type {module:model/MessageContentImageFileObject.TypeEnum} Always `image_file`.
   * @param imageFile {module:model/MessageContentImageFileObjectImageFile} 
   */
  constructor(type, imageFile) {
    this.type = type;
    this.imageFile = imageFile;
  }

  /**
   * Constructs a <code>MessageContentImageFileObject</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MessageContentImageFileObject} obj Optional instance to populate.
   * @return {module:model/MessageContentImageFileObject} The populated <code>MessageContentImageFileObject</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new MessageContentImageFileObject();
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'String');
      if (data.hasOwnProperty('image_file'))
        obj.imageFile = MessageContentImageFileObjectImageFile.constructFromObject(data['image_file']);
    }
    return obj;
  }
}

/**
 * Allowed values for the <code>type</code> property.
 * @enum {String}
 * @readonly
 */
MessageContentImageFileObject.TypeEnum = {
  /**
   * value: "image_file"
   * @const
   */
  imageFile: "image_file"
};
/**
 * Always `image_file`.
 * @member {module:model/MessageContentImageFileObject.TypeEnum} type
 */
MessageContentImageFileObject.prototype.type = undefined;

/**
 * @member {module:model/MessageContentImageFileObjectImageFile} imageFile
 */
MessageContentImageFileObject.prototype.imageFile = undefined;

// Implement OneOfMessageObjectContentItems interface:
