/*
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.50
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The RunObjectLastError model module.
 * @module model/RunObjectLastError
 * @version 2.0.0
 */
export class RunObjectLastError {
  /**
   * Constructs a new <code>RunObjectLastError</code>.
   * The last error associated with this run. Will be &#x60;null&#x60; if there are no errors.
   * @alias module:model/RunObjectLastError
   * @class
   * @param code {module:model/RunObjectLastError.CodeEnum} One of `server_error` or `rate_limit_exceeded`.
   * @param message {String} A human-readable description of the error.
   */
  constructor(code, message) {
    this.code = code;
    this.message = message;
  }

  /**
   * Constructs a <code>RunObjectLastError</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RunObjectLastError} obj Optional instance to populate.
   * @return {module:model/RunObjectLastError} The populated <code>RunObjectLastError</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new RunObjectLastError();
      if (data.hasOwnProperty('code'))
        obj.code = ApiClient.convertToType(data['code'], 'String');
      if (data.hasOwnProperty('message'))
        obj.message = ApiClient.convertToType(data['message'], 'String');
    }
    return obj;
  }
}

/**
 * Allowed values for the <code>code</code> property.
 * @enum {String}
 * @readonly
 */
RunObjectLastError.CodeEnum = {
  /**
   * value: "server_error"
   * @const
   */
  serverError: "server_error",

  /**
   * value: "rate_limit_exceeded"
   * @const
   */
  rateLimitExceeded: "rate_limit_exceeded"
};
/**
 * One of `server_error` or `rate_limit_exceeded`.
 * @member {module:model/RunObjectLastError.CodeEnum} code
 */
RunObjectLastError.prototype.code = undefined;

/**
 * A human-readable description of the error.
 * @member {String} message
 */
RunObjectLastError.prototype.message = undefined;

