/*
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.50
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {RunToolCallObject} from './RunToolCallObject';

/**
 * The RunObjectRequiredActionSubmitToolOutputs model module.
 * @module model/RunObjectRequiredActionSubmitToolOutputs
 * @version 2.0.0
 */
export class RunObjectRequiredActionSubmitToolOutputs {
  /**
   * Constructs a new <code>RunObjectRequiredActionSubmitToolOutputs</code>.
   * Details on the tool outputs needed for this run to continue.
   * @alias module:model/RunObjectRequiredActionSubmitToolOutputs
   * @class
   * @param toolCalls {Array.<module:model/RunToolCallObject>} A list of the relevant tool calls.
   */
  constructor(toolCalls) {
    this.toolCalls = toolCalls;
  }

  /**
   * Constructs a <code>RunObjectRequiredActionSubmitToolOutputs</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RunObjectRequiredActionSubmitToolOutputs} obj Optional instance to populate.
   * @return {module:model/RunObjectRequiredActionSubmitToolOutputs} The populated <code>RunObjectRequiredActionSubmitToolOutputs</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new RunObjectRequiredActionSubmitToolOutputs();
      if (data.hasOwnProperty('tool_calls'))
        obj.toolCalls = ApiClient.convertToType(data['tool_calls'], [RunToolCallObject]);
    }
    return obj;
  }
}

/**
 * A list of the relevant tool calls.
 * @member {Array.<module:model/RunToolCallObject>} toolCalls
 */
RunObjectRequiredActionSubmitToolOutputs.prototype.toolCalls = undefined;

