/*
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.50
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {RunStepDetailsToolCallsFunctionObjectFunction} from './RunStepDetailsToolCallsFunctionObjectFunction';

/**
 * The RunStepDetailsToolCallsFunctionObject model module.
 * @module model/RunStepDetailsToolCallsFunctionObject
 * @version 2.0.0
 */
export class RunStepDetailsToolCallsFunctionObject {
  /**
   * Constructs a new <code>RunStepDetailsToolCallsFunctionObject</code>.
   * @alias module:model/RunStepDetailsToolCallsFunctionObject
   * @class
   * @param id {String} The ID of the tool call object.
   * @param type {module:model/RunStepDetailsToolCallsFunctionObject.TypeEnum} The type of tool call. This is always going to be `function` for this type of tool call.
   * @param _function {module:model/RunStepDetailsToolCallsFunctionObjectFunction} 
   */
  constructor(id, type, _function) {
    this.id = id;
    this.type = type;
    this._function = _function;
  }

  /**
   * Constructs a <code>RunStepDetailsToolCallsFunctionObject</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RunStepDetailsToolCallsFunctionObject} obj Optional instance to populate.
   * @return {module:model/RunStepDetailsToolCallsFunctionObject} The populated <code>RunStepDetailsToolCallsFunctionObject</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new RunStepDetailsToolCallsFunctionObject();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'String');
      if (data.hasOwnProperty('function'))
        obj._function = RunStepDetailsToolCallsFunctionObjectFunction.constructFromObject(data['function']);
    }
    return obj;
  }
}

/**
 * The ID of the tool call object.
 * @member {String} id
 */
RunStepDetailsToolCallsFunctionObject.prototype.id = undefined;

/**
 * Allowed values for the <code>type</code> property.
 * @enum {String}
 * @readonly
 */
RunStepDetailsToolCallsFunctionObject.TypeEnum = {
  /**
   * value: "function"
   * @const
   */
  _function: "function"
};
/**
 * The type of tool call. This is always going to be `function` for this type of tool call.
 * @member {module:model/RunStepDetailsToolCallsFunctionObject.TypeEnum} type
 */
RunStepDetailsToolCallsFunctionObject.prototype.type = undefined;

/**
 * @member {module:model/RunStepDetailsToolCallsFunctionObjectFunction} _function
 */
RunStepDetailsToolCallsFunctionObject.prototype._function = undefined;

// Implement OneOfRunStepDetailsToolCallsObjectToolCallsItems interface:
