/*
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.50
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The RunStepDetailsToolCallsCodeOutputImageObjectImage model module.
 * @module model/RunStepDetailsToolCallsCodeOutputImageObjectImage
 * @version 2.0.0
 */
export class RunStepDetailsToolCallsCodeOutputImageObjectImage {
  /**
   * Constructs a new <code>RunStepDetailsToolCallsCodeOutputImageObjectImage</code>.
   * @alias module:model/RunStepDetailsToolCallsCodeOutputImageObjectImage
   * @class
   * @param fileId {String} The [file](/docs/api-reference/files) ID of the image.
   */
  constructor(fileId) {
    this.fileId = fileId;
  }

  /**
   * Constructs a <code>RunStepDetailsToolCallsCodeOutputImageObjectImage</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RunStepDetailsToolCallsCodeOutputImageObjectImage} obj Optional instance to populate.
   * @return {module:model/RunStepDetailsToolCallsCodeOutputImageObjectImage} The populated <code>RunStepDetailsToolCallsCodeOutputImageObjectImage</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new RunStepDetailsToolCallsCodeOutputImageObjectImage();
      if (data.hasOwnProperty('file_id'))
        obj.fileId = ApiClient.convertToType(data['file_id'], 'String');
    }
    return obj;
  }
}

/**
 * The [file](/docs/api-reference/files) ID of the image.
 * @member {String} fileId
 */
RunStepDetailsToolCallsCodeOutputImageObjectImage.prototype.fileId = undefined;

