/*
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.50
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The RunStepDetailsToolCallsObject model module.
 * @module model/RunStepDetailsToolCallsObject
 * @version 2.0.0
 */
export class RunStepDetailsToolCallsObject {
  /**
   * Constructs a new <code>RunStepDetailsToolCallsObject</code>.
   * Details of the tool call.
   * @alias module:model/RunStepDetailsToolCallsObject
   * @class
   * @param type {module:model/RunStepDetailsToolCallsObject.TypeEnum} Always `tool_calls`.
   * @param toolCalls {Array.<Object>} An array of tool calls the run step was involved in. These can be associated with one of three types of tools: `code_interpreter`, `retrieval`, or `function`. 
   */
  constructor(type, toolCalls) {
    this.type = type;
    this.toolCalls = toolCalls;
  }

  /**
   * Constructs a <code>RunStepDetailsToolCallsObject</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RunStepDetailsToolCallsObject} obj Optional instance to populate.
   * @return {module:model/RunStepDetailsToolCallsObject} The populated <code>RunStepDetailsToolCallsObject</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new RunStepDetailsToolCallsObject();
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'String');
      if (data.hasOwnProperty('tool_calls'))
        obj.toolCalls = ApiClient.convertToType(data['tool_calls'], [OneOfRunStepDetailsToolCallsObjectToolCallsItems]);
    }
    return obj;
  }
}

/**
 * Allowed values for the <code>type</code> property.
 * @enum {String}
 * @readonly
 */
RunStepDetailsToolCallsObject.TypeEnum = {
  /**
   * value: "tool_calls"
   * @const
   */
  toolCalls: "tool_calls"
};
/**
 * Always `tool_calls`.
 * @member {module:model/RunStepDetailsToolCallsObject.TypeEnum} type
 */
RunStepDetailsToolCallsObject.prototype.type = undefined;

/**
 * An array of tool calls the run step was involved in. These can be associated with one of three types of tools: `code_interpreter`, `retrieval`, or `function`. 
 * @member {Array.<Object>} toolCalls
 */
RunStepDetailsToolCallsObject.prototype.toolCalls = undefined;

// Implement OneOfRunStepObjectStepDetails interface:
