/*
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.50
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The RunStepDetailsMessageCreationObjectMessageCreation model module.
 * @module model/RunStepDetailsMessageCreationObjectMessageCreation
 * @version 2.0.0
 */
export class RunStepDetailsMessageCreationObjectMessageCreation {
  /**
   * Constructs a new <code>RunStepDetailsMessageCreationObjectMessageCreation</code>.
   * @alias module:model/RunStepDetailsMessageCreationObjectMessageCreation
   * @class
   * @param messageId {String} The ID of the message that was created by this run step.
   */
  constructor(messageId) {
    this.messageId = messageId;
  }

  /**
   * Constructs a <code>RunStepDetailsMessageCreationObjectMessageCreation</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RunStepDetailsMessageCreationObjectMessageCreation} obj Optional instance to populate.
   * @return {module:model/RunStepDetailsMessageCreationObjectMessageCreation} The populated <code>RunStepDetailsMessageCreationObjectMessageCreation</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new RunStepDetailsMessageCreationObjectMessageCreation();
      if (data.hasOwnProperty('message_id'))
        obj.messageId = ApiClient.convertToType(data['message_id'], 'String');
    }
    return obj;
  }
}

/**
 * The ID of the message that was created by this run step.
 * @member {String} messageId
 */
RunStepDetailsMessageCreationObjectMessageCreation.prototype.messageId = undefined;

