/*
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.50
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The RunStepDetailsToolCallsRetrievalObject model module.
 * @module model/RunStepDetailsToolCallsRetrievalObject
 * @version 2.0.0
 */
export class RunStepDetailsToolCallsRetrievalObject {
  /**
   * Constructs a new <code>RunStepDetailsToolCallsRetrievalObject</code>.
   * @alias module:model/RunStepDetailsToolCallsRetrievalObject
   * @class
   * @param id {String} The ID of the tool call object.
   * @param type {module:model/RunStepDetailsToolCallsRetrievalObject.TypeEnum} The type of tool call. This is always going to be `retrieval` for this type of tool call.
   * @param retrieval {Object} For now, this is always going to be an empty object.
   */
  constructor(id, type, retrieval) {
    this.id = id;
    this.type = type;
    this.retrieval = retrieval;
  }

  /**
   * Constructs a <code>RunStepDetailsToolCallsRetrievalObject</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RunStepDetailsToolCallsRetrievalObject} obj Optional instance to populate.
   * @return {module:model/RunStepDetailsToolCallsRetrievalObject} The populated <code>RunStepDetailsToolCallsRetrievalObject</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new RunStepDetailsToolCallsRetrievalObject();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'String');
      if (data.hasOwnProperty('retrieval'))
        obj.retrieval = ApiClient.convertToType(data['retrieval'], Object);
    }
    return obj;
  }
}

/**
 * The ID of the tool call object.
 * @member {String} id
 */
RunStepDetailsToolCallsRetrievalObject.prototype.id = undefined;

/**
 * Allowed values for the <code>type</code> property.
 * @enum {String}
 * @readonly
 */
RunStepDetailsToolCallsRetrievalObject.TypeEnum = {
  /**
   * value: "retrieval"
   * @const
   */
  retrieval: "retrieval"
};
/**
 * The type of tool call. This is always going to be `retrieval` for this type of tool call.
 * @member {module:model/RunStepDetailsToolCallsRetrievalObject.TypeEnum} type
 */
RunStepDetailsToolCallsRetrievalObject.prototype.type = undefined;

/**
 * For now, this is always going to be an empty object.
 * @member {Object} retrieval
 */
RunStepDetailsToolCallsRetrievalObject.prototype.retrieval = undefined;

// Implement OneOfRunStepDetailsToolCallsObjectToolCallsItems interface:
