/*
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.50
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The RunToolCallObjectFunction model module.
 * @module model/RunToolCallObjectFunction
 * @version 2.0.0
 */
export class RunToolCallObjectFunction {
  /**
   * Constructs a new <code>RunToolCallObjectFunction</code>.
   * The function definition.
   * @alias module:model/RunToolCallObjectFunction
   * @class
   * @param name {String} The name of the function.
   * @param _arguments {String} The arguments that the model expects you to pass to the function.
   */
  constructor(name, _arguments) {
    this.name = name;
    this._arguments = _arguments;
  }

  /**
   * Constructs a <code>RunToolCallObjectFunction</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RunToolCallObjectFunction} obj Optional instance to populate.
   * @return {module:model/RunToolCallObjectFunction} The populated <code>RunToolCallObjectFunction</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new RunToolCallObjectFunction();
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('arguments'))
        obj._arguments = ApiClient.convertToType(data['arguments'], 'String');
    }
    return obj;
  }
}

/**
 * The name of the function.
 * @member {String} name
 */
RunToolCallObjectFunction.prototype.name = undefined;

/**
 * The arguments that the model expects you to pass to the function.
 * @member {String} _arguments
 */
RunToolCallObjectFunction.prototype._arguments = undefined;

