/*
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.50
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {SubmitToolOutputsRunRequestToolOutputs} from './SubmitToolOutputsRunRequestToolOutputs';

/**
 * The SubmitToolOutputsRunRequest model module.
 * @module model/SubmitToolOutputsRunRequest
 * @version 2.0.0
 */
export class SubmitToolOutputsRunRequest {
  /**
   * Constructs a new <code>SubmitToolOutputsRunRequest</code>.
   * @alias module:model/SubmitToolOutputsRunRequest
   * @class
   * @param toolOutputs {Array.<module:model/SubmitToolOutputsRunRequestToolOutputs>} A list of tools for which the outputs are being submitted.
   */
  constructor(toolOutputs) {
    this.toolOutputs = toolOutputs;
  }

  /**
   * Constructs a <code>SubmitToolOutputsRunRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SubmitToolOutputsRunRequest} obj Optional instance to populate.
   * @return {module:model/SubmitToolOutputsRunRequest} The populated <code>SubmitToolOutputsRunRequest</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new SubmitToolOutputsRunRequest();
      if (data.hasOwnProperty('tool_outputs'))
        obj.toolOutputs = ApiClient.convertToType(data['tool_outputs'], [SubmitToolOutputsRunRequestToolOutputs]);
    }
    return obj;
  }
}

/**
 * A list of tools for which the outputs are being submitted.
 * @member {Array.<module:model/SubmitToolOutputsRunRequestToolOutputs>} toolOutputs
 */
SubmitToolOutputsRunRequest.prototype.toolOutputs = undefined;

