/*
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.50
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from "../ApiClient";
import {CreateModerationRequest} from '../model/CreateModerationRequest';
import {CreateModerationResponse} from '../model/CreateModerationResponse';

/**
* Moderations service.
* @module api/ModerationsApi
* @version 2.0.0
*/
export class ModerationsApi {

    /**
    * Constructs a new ModerationsApi. 
    * @alias module:api/ModerationsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the createModeration operation.
     * @callback moduleapi/ModerationsApi~createModerationCallback
     * @param {String} error Error message, if any.
     * @param {module:model/CreateModerationResponse{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Classifies if text violates OpenAI&#x27;s Content Policy
     * @param {module:model/CreateModerationRequest} body 
     * @param {module:api/ModerationsApi~createModerationCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    createModeration(body, callback) {
      
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling createModeration");
      }

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = CreateModerationResponse;

      return this.apiClient.callApi(
        '/moderations', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}