/*
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.50
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OpenAiApi);
  }
}(this, function(expect, OpenAiApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('Image', function() {
      beforeEach(function() {
        instance = new OpenAiApi.Image();
      });

      it('should create an instance of Image', function() {
        // TODO: update the code to test Image
        expect(instance).to.be.a(OpenAiApi.Image);
      });

      it('should have the property b64Json (base name: "b64_json")', function() {
        // TODO: update the code to test the property b64Json
        expect(instance).to.have.property('b64Json');
        // expect(instance.b64Json).to.be(expectedValueLiteral);
      });

      it('should have the property url (base name: "url")', function() {
        // TODO: update the code to test the property url
        expect(instance).to.have.property('url');
        // expect(instance.url).to.be(expectedValueLiteral);
      });

      it('should have the property revisedPrompt (base name: "revised_prompt")', function() {
        // TODO: update the code to test the property revisedPrompt
        expect(instance).to.have.property('revisedPrompt');
        // expect(instance.revisedPrompt).to.be(expectedValueLiteral);
      });

    });
  });

}));
