/*
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.50
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OpenAiApi);
  }
}(this, function(expect, OpenAiApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OpenAiApi.AudioApi();
  });

  describe('(package)', function() {
    describe('AudioApi', function() {
      describe('createSpeech', function() {
        it('should call createSpeech successfully', function(done) {
          // TODO: uncomment, update parameter values for createSpeech call and complete the assertions
          /*

          instance.createSpeech(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Blob);
            // expect(data).to.be(null);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('createTranscription', function() {
        it('should call createTranscription successfully', function(done) {
          // TODO: uncomment, update parameter values for createTranscription call and complete the assertions
          /*

          instance.createTranscription(file, model, language, prompt, responseFormat, temperature, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(OpenAiApi.CreateTranscriptionResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('createTranslation', function() {
        it('should call createTranslation successfully', function(done) {
          // TODO: uncomment, update parameter values for createTranslation call and complete the assertions
          /*

          instance.createTranslation(file, model, prompt, responseFormat, temperature, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(OpenAiApi.CreateTranslationResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
