/*
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.50
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OpenAiApi);
  }
}(this, function(expect, OpenAiApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OpenAiApi.FineTuningApi();
  });

  describe('(package)', function() {
    describe('FineTuningApi', function() {
      describe('cancelFineTuningJob', function() {
        it('should call cancelFineTuningJob successfully', function(done) {
          // TODO: uncomment, update parameter values for cancelFineTuningJob call and complete the assertions
          /*

          instance.cancelFineTuningJob(fineTuningJobId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(OpenAiApi.FineTuningJob);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('createFineTuningJob', function() {
        it('should call createFineTuningJob successfully', function(done) {
          // TODO: uncomment, update parameter values for createFineTuningJob call and complete the assertions
          /*

          instance.createFineTuningJob(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(OpenAiApi.FineTuningJob);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('listFineTuningEvents', function() {
        it('should call listFineTuningEvents successfully', function(done) {
          // TODO: uncomment, update parameter values for listFineTuningEvents call and complete the assertions
          /*
          var opts = {};

          instance.listFineTuningEvents(fineTuningJobId, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(OpenAiApi.ListFineTuningJobEventsResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('listPaginatedFineTuningJobs', function() {
        it('should call listPaginatedFineTuningJobs successfully', function(done) {
          // TODO: uncomment, update parameter values for listPaginatedFineTuningJobs call and complete the assertions
          /*
          var opts = {};

          instance.listPaginatedFineTuningJobs(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(OpenAiApi.ListPaginatedFineTuningJobsResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('retrieveFineTuningJob', function() {
        it('should call retrieveFineTuningJob successfully', function(done) {
          // TODO: uncomment, update parameter values for retrieveFineTuningJob call and complete the assertions
          /*

          instance.retrieveFineTuningJob(fineTuningJobId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(OpenAiApi.FineTuningJob);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
